# -*- coding: utf-8 -*-
"""Build achievement Exact translations into workbench ui_exact / overlay extras."""
from __future__ import annotations

import csv
from pathlib import Path

OUT = Path("loc/workbench/achievements.csv")

# title -> zh, desc -> zh (all unique Exact keys)
ACH = {
    "Achievements": "成就",
    "All": "全部",
    "On Your Way": "初出茅庐",
    "Win a game.": "赢得一局游戏。",
    "First Beatdown": "首次击败",
    "Win a game against another player": "对战其他玩家并获胜",
    "The Benjamin": "百战老兵",
    "Win 100 games": "赢得 100 局游戏",
    "Hot Streak": "连胜热潮",
    "Win 10 games in a row": "连胜 10 局",
    "Cult Friendly": "邪教之友",
    "Win 10 games without killing the Cultist": "不击败邪教徒的情况下赢得 10 局",
    "Assassin": "刺客",
    "Win 10 games in a row against other players": "对战其他玩家连胜 10 局",
    "Cult Killer": "邪教克星",
    "Kill the Cultist 1000 times": "击败邪教徒 1000 次",
    "Recruiter": "征召官",
    "Acquire 1000 center row Heroes": "获取 1000 张中央牌列英雄",
    "Builder": "建造者",
    "Play 1000 Constructs": "打出 1000 件神器",
    "Vanquisher": "征服者",
    "Defeat 1000 center row Monsters": "击败 1000 只中央牌列怪物",
    "Over 9000!!": "超过九千！！",
    "Gain 9001 honor points": "获得 9001 点荣誉",
    "Have Everything (CotG)": "应有尽有（弑神）",
    "Acquire or defeat every card in Chronicle of the Godslayer": "获取或击败《弑神编年史》中的每一张牌",
    "Have Everything (RotF)": "应有尽有（归来）",
    "Acquire or defeat every card in Return of the Fallen": "获取或击败《堕落者归来》中的每一张牌",
    "Have Everything (SoS)": "应有尽有（风暴）",
    "Acquire or defeat every card in Storm of Souls": "获取或击败《灵魂风暴》中的每一张牌",
    "Yoink!": "抢！",
    "Defeat Xeron, Duke of Lies in a 4 player game": "在 4 人局中击败谎言之公爵泽伦",
    "Lucky Godslayer": "幸运弑神者",
    "Acquire Hedron Cannon after defeating Avatar of the Fallen that turn": "本回合击败堕落化身后获取赫德隆加农",
    "Weapon X": "武器 X",
    "Time Traveler": "时间旅人",
    "Have at least one of each Mechana construct from Chronicle of the Godslayer in play at the same time": "同时在场至少各一件《弑神编年史》的机械神器",
    "You Must Be Aaron": "你一定是亚伦",
    "Defeat Avatar of the Fallen and Samael the Fallen in the same turn": "同一回合击败堕落化身与堕落者萨麦尔",
    "Don't Mind If Adayu": "阿达尤不介意",
    "Time Machine": "时间机器",
    "Defeat Samael the Fallen with Adayu": "用阿达尤击败堕落者萨麦尔",
    "Monster Mash": "怪物盛宴",
    "Have one of each Return of the Fallen Monster in your deck while Samael is in play": "萨麦尔在场时，牌库中各有一只《堕落者归来》怪物",
    "Dream Big": "大胆做梦",
    "Acquire Dream Machine with P.R.I.M.E.": "用 P.R.I.M.E. 获取梦境机器",
    "Livin' On The Edge": "刀锋边缘",
    "Have Umbral edge and Penumbral Edge in play at the same time": "同时让暗影刃与半影刃在场",
    "Trophy Room": "战利品室",
    "Have one of each trophy monster in play at the same time while playing with Storm of Souls": "使用《灵魂风暴》时同时控制每种战利品怪物各一只",
    "United We Stand": "众志成城",
    "Play 5 Lifebound heroes in a single turn while playing with only Storm of Souls": "仅用《灵魂风暴》时，同一回合打出 5 张命约英雄",
    "Catch 'em all!": "全部抓住！",
    "Defeat all 5 Growmites in the same game": "同一局击败全部 5 只生长螨",
    "Beastly Staff": "野兽之杖",
    "Gain 5 Honor or more from the reveal of Beast Staff": "从野兽之杖的展示中获得 5 点或更多荣誉",
    "Soul Collector": "灵魂收集者",
    "Use each of the Soul Gems": "使用每一种灵魂宝石",
    "Soul Fire": "灵魂之火",
    "Play 5 Soul Gems in 1 turn": "同一回合打出 5 枚灵魂宝石",
    "Tag Team": "双打搭档",
    "Take an extra turn with Wandering Askara": "用流浪阿斯卡拉获得额外回合",
    "Treasure Trove": "珍宝库",
    "Acquire five or more treasure in the same turn": "同一回合获取五件或更多宝藏",
    "Energizer Bunny": "劲量兔",
    "Gain 10 energy in one turn": "同一回合获得 10 点能量",
    "Harbinger Of Winning": "胜利先兆",
    "Defeat and Energize Herald of Doom": "击败并充能末日使者",
    "B.F. Sword": "大剑",
    "Defeat five monsters in a single turn with Oziah": "用奥齐亚在同一回合击败五只怪物",
    "Freebee": "白嫖",
    "Acquire Oziah for free with Energy": "用能量免费获取奥齐亚",
    "More Than Meets The Eye": "远不止表面",
    "Yolo Twice": "再赌一把",
    "Transform all of the cards in Darkness Unleashed": "转化《黑暗释放》中的所有卡牌",
    "Greedy Treasure Hunter": "贪婪寻宝者",
    "Have Moken the Huntsmaster in your deck with at least 10 treasures": "牌库中有猎主莫肯且至少有 10 件宝藏",
    "Cobra King Midas": "眼镜蛇迈达斯",
    "Serenity Now": "此刻宁静",
    "Gain 20 Honor in a single turn with Jakeb, Cobra King": "用眼镜蛇王杰克布在同一回合获得 20 荣誉",
    "Stay Focused": "保持专注",
    "Follow The Leader": "跟随领袖",
    "Win a game with only two factions in your deck while playing with only Realms Unraveled": "仅用《诸界瓦解》且牌库只有两个派系时获胜",
    "Ouch, That Stings": "哎哟，真刺",
    "Defeat a Monster in the Center Row with Emri's Sting and Emri, Demonsbane": "用艾姆瑞之蛰与恶魔克星艾姆瑞击败中央牌列怪物",
    "Glutton For Punishment": "自讨苦吃",
    "Defeat Aranyx, the Glutton and Xeron, Lord of Deofol on the same turn": "同一回合击败贪食者阿兰尼克斯与迪奥弗之主泽伦",
    "Three Cannon Salute": "三炮齐鸣",
    "Play Hedron Cannon, Plasma Cannon, and Canon Templar on the same turn": "同一回合打出赫德隆加农、等离子加农与教典圣殿武士",
    "Champion Of Champions": "冠军中的冠军",
    "Win a game with each of the Champions": "以每位冠军各赢得一局",
    "Dream On": "继续做梦",
    "Acquire all Vision cards in Dreamscape": "获取《梦境》中的全部幻视牌",
    "Living The Dream": "活在梦里",
    "Acquire two Dream Vision cards without paying their cost during a single game": "同一局中无需支付费用获取两张梦境幻视牌",
    "Wicked Game": "险恶游戏",
    "Use Wicked End to defeat Ender of Days": "用险恶终结击败末日终结者",
    "Pasythea Go": "帕西提亚出发",
    "Acquire Pasythea, the Aegis using Pasythea's Ward": "用帕西提亚护符获取神盾帕西提亚",
    "Born Again": "重生",
    "Acquire all Dreamborn cards in Dreamscape": "获取《梦境》中的全部梦生牌",
    "All Day, All Night": "日日夜夜",
    "Gain a DAY bonus and a NIGHT bonus in the same turn": "同一回合获得昼奖励与夜奖励",
    "Hunting Party": "狩猎小队",
    "Play Flare Tracker and Sureshot Tracker in the same turn": "同一回合打出闪光追踪者与神射手追踪者",
    "Master Assassin": "大师刺客",
    "Play Deadeye Assassin with 10 or more Void cards in your discard pile": "弃牌堆有 10 张或更多虚空卡牌时打出神射手刺客",
    "Night Owl": "夜猫子",
    "Win a game where the only cards you've acquired are Night cards": "所获取卡牌全为夜牌时获胜",
    "Piper at the Gates of Dawn": "黎明之门的吹笛人",
    "Win a game where the only cards you've acquired are Day cards": "所获取卡牌全为昼牌时获胜",
    "The Fifth Elements": "第五元素",
    "Acquire all five of the Transformed Events/Heroes across multiple games": "在多局中获取全部五种已转化事件/英雄",
    "P.R.I.M.E.'d for Victory": "P.R.I.M.E. 制胜",
    "Win a game as a result of P.R.I.M.E. Directive": "因 P.R.I.M.E. 指令获胜",
    "Don't Feed Them After Midnight": "午夜后别喂它们",
    "Clean Bill of Health": "体检全绿",
    "Win a game with no Infest cards in your deck using Gift of the Elements": "使用《元素恩赐》且牌库无感染牌时获胜",
    "Ascension: A Deck Empowering Game": "创升：牌库赋能游戏",
    "Win a game with 5 or fewer cards in your deck": "牌库中卡牌不超过 5 张时获胜",
    "I Guess It Just Froze Over": "想来地狱结冰了",
    "Defeat five Hellfrost Imps on a single turn": "同一回合击败五只狱霜小恶魔",
    "Whoa. Whoa. Whoa. What are you doing?": "等等等等，你在干什么？",
    "Take all three Temples from your opponent(s) on the final turn of the game and win": "终局回合夺走对手全部三座神殿并获胜",
    "Jubilee!": "狂欢！",
    "Using only Valley of the Ancients, draw your entire deck using Jubilant Monk": "仅用《远古山谷》，用欢喜僧抽光整个牌库",
    "Devil's Triangle": "魔鬼三角",
    "Roll three 6s on the Delirium Die in a single game": "同一局在谵妄骰上掷出三次 6",
    "Draaaaaaaw!": "抽——牌！",
    "Using Dhartha, Mechamonk, draw seven or more cards in a single turn": "用达萨·机械僧在同一回合抽七张或更多牌",
    "Deja Vu": "似曾相识",
    "Use the Recur effect found on all cards with a Recur effect in Delirium": "使用《谵妄》中所有带复发效果卡牌的复发",
    "Deal With It": "认了吧",
    "Roll the Delirium Die using the Dream Dealer's effect": "用梦境庄家的效果掷谵妄骰",
    "A Complete Transformation": "完全转化",
    "Transform all of the cards in Deliverance": "转化《救赎》中的所有卡牌",
    "God Of Plunder": "掠夺之神",
    "Activate the Plunder effect five times in a single game": "同一局发动掠夺效果五次",
    "The Tall Man Approves": "高个儿点头",
    "Activate the Phantasm effect five times in a single game": "同一局发动幻影效果五次",
    "Four Of Swords": "宝剑四",
    "Acquire Pasythea, The Redeemed for free": "免费获取被救赎的帕西提亚",
    "Soul Sisters": "灵魂姐妹",
    "Play \"Naka, Emri's Chosen\" and \"Emri, Soulstealer\" on the same turn": "同一回合打出「纳卡·艾姆瑞的天选者」与「窃魂者艾姆瑞」",
    "Shackled": "镣铐",
    "Using only Deliverance, finish a game with only Dreambind cards in your deck": "仅用《救赎》，终局时牌库只有梦缚牌",
    "A Legend Among Legends": "传奇中的传奇",
    "Reach Legendary Status with all Legendary Characters": "使所有传奇角色达到传奇地位",
    "Messenger Mandate": "使者敕令",
    "Win the game with the effect of Arha Emissary": "用亚哈使者的效果赢得游戏",
    "Thrice Reborn": "三度重生",
    "Play Mechaphoenix three times in one turn": "同一回合打出机械凤凰三次",
    "Monkopoly": "僧侣垄断",
    "Play Dark Monk, Psionic Monk, and Monk of the Stone Circle in the same turn": "同一回合打出暗僧、灵能僧与石环僧",
    "Boon Balloon": "恩赐气球",
    "Use a Boon from every faction in one turn": "同一回合使用每个派系的恩赐各一次",
    "Win two Fate Auctions on a single turn.": "同一回合赢得两次天命拍卖。",
    "Monsters? You Don't Need No Stinkin' Monsters": "怪物？才不需要那些臭怪物",
    "Gain more than 20 Honor by playing a single card": "打出单张牌获得超过 20 荣誉",
}


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["en", "zh"])
        for en, zh in sorted(ACH.items(), key=lambda x: x[0].lower()):
            w.writerow([en, zh])
    print("wrote", len(ACH), "->", OUT)


if __name__ == "__main__":
    main()
