"""Exact names and word-level lexicon for leftover English card titles."""

from __future__ import annotations

# Full titles first (longest match). Proper names follow 暗杀神 / 创升纪元 usage.
NAME_EXACT: dict[str, str] = {
    "Kor, the Ferromancer": "铁术师科尔",
    "Xeron, Duke of Lies": "谎言之公爵泽伦",
    "HSedron Rising": "多面体崛起",
    "Madness' Embrace": "疯狂之拥",
    "Rut, Oaken Master": "橡木大师鲁特",
    "Death's Widow": "死亡寡妇",
    "Druid's Wreath": "德鲁伊花环",
    "Shade's Bargain": "暗影交易",
    "Arbiter's Censer": "仲裁者香炉",
    "Dreamer's Glass": "梦者琉璃",
    "Cell Block E": "牢房E区",
    "Adayu, the Chosen": "天选者阿达尤",
    "Nairi, Henge Queen": "环石女王奈莉",
    "Sadranis, Dark Emissary": "黑暗使者萨德拉尼斯",
    "Bazu, Duke of Scorn": "轻蔑公爵巴祖",
    "Raj, Psionic Master": "灵能大师拉吉",
    "Tarik, the Trickster": "诡术师塔里克",
    "Syril, Runic Alpha": "符文首领西里尔",
    "Emri, Soulslayer": "斩魂者艾姆瑞",
    "Emri, the Unmaker": "解构者艾姆瑞",
    "Emri, Demonsbane": "恶魔克星艾姆瑞",
    "Emri, Shadowslayer": "斩影者艾姆瑞",
    "Emri, Born of Battle": "战生艾姆瑞",
    "Emri, Lightbringer": "携光者艾姆瑞",
    "Emri, Soulstealer": "窃魂者艾姆瑞",
    "Cetra, Weaver of Stars": "织星者塞特拉",
    "Cetra, Benefactor of All": "万民之恩塞特拉",
    "Cetra, Matron of Stars": "星辰主母塞特拉",
    "Cetra, Celestial Body": "天体塞特拉",
    "Cetra, Voidmother": "虚空之母塞特拉",
    "Cetra, Guide of Ogo": "奥戈向导塞特拉",
    "Oziah, Judge of Logos": "逻各斯审判者奥齐亚",
    "Oziah the Peerless": "无双的奥齐亚",
    "P.R.I.M.E. Directive": "P.R.I.M.E.指令",
    "P.R.I.M.E.": "P.R.I.M.E.",
    "Legendary Boon: Enlightened": "传奇恩赐：启迪",
    "Legendary Boon: Lifebound": "传奇恩赐：生命",
    "Legendary Boon: Mechana": "传奇恩赐：机械",
    "Legendary Boon: Void": "传奇恩赐：虚空",
    "Destroyer's Gate": "毁灭者之门",
    "Hedron Rising": "多面体崛起",
    "Arha Rising": "亚哈崛起",
    "Ogo Rising": "奥戈崛起",
    "Void Rising": "虚空崛起",
    "Rise of the Cult": "邪教崛起",
    "Unchained Fates": "挣脱的命运",
    "Souls Unbound": "灵魂解缚",
    "Clutch of Darkness": "黑暗之握",
    "Call of Darkness": "黑暗呼唤",
    "Ashes to Ashes": "灰烬归于灰烬",
    "Dust to Dust": "尘土归于尘土",
    "Always Available": "始终可用",
    "Temple of Immortality": "不朽神殿",
    "Temple of Heroes": "英雄神殿",
    "Temple of Life": "生命神殿",
    "Temple of Death": "死亡神殿",
    "Temple of the Wind": "风之神殿",
    "Map of the Stars": "星图",
    "Eye of Potential": "潜能之眼",
    "Eye of Destiny": "命运之眼",
    "Chronicle of Vigil": "祈夜编年史",
    "Vigil's Resolve": "祈夜的决意",
    "Nothing Man": "虚无之人",
    "The World Tree": "世界树",
    "The Great Eclipse": "大日食",
    "The Grand Design": "宏伟设计",
    "The All-Seeing Eye": "全视之眼",
    "The Ironheart": "铁之心",
    "The Iron Seven": "钢铁七人",
    "The Chrome Circle": "铬环",
    "The Dreamscrape": "刮梦者",
    "The Dragon's Eye": "龙之眼",
    "The Aethermourne": "以太哀歌",
    "Landis' Potions & Pies": "兰迪斯的药剂与馅饼",
    "N.I.N.E.": "N.I.N.E.",
    "Rūt, Oaken Master": "橡木大师鲁特",
    "Vezra'Tull, The Voidwyrm": "虚空巨虫维兹拉图尔",
    "Kythis, Rebel Godling v2": "叛神子凯西斯",
    "Astrolabe TRX": "星盘TRX",
    "Astroblade TRX": "星刃TRX",
}

# Longest-first phrases inside titles.
NAME_PARTS: list[tuple[str, str]] = [
    ("Black Watch Elite", "黑卫精锐"),
    ("Black Watch Exemplar", "黑卫典范"),
    ("Black Watch", "黑卫"),
    ("Lidless Eye", "无目之眼"),
    ("Stone Circle Elder", "石环长老"),
    ("Stone Circle", "石环"),
    ("Duke of Lies", "谎言之公爵"),
    ("Duke of Scorn", "轻蔑公爵"),
    ("Lord of Deofol", "迪奥福尔之主"),
    ("Paragon of Strife", "争斗典范"),
    ("Judge of Logos", "逻各斯审判者"),
    ("Handmaiden of Logos", "逻各斯侍女"),
    ("Matron of Stars", "星辰主母"),
    ("Matron of Discovery", "发现主母"),
    ("Benefactor of All", "万民之恩"),
    ("Weaver of Stars", "织星者"),
    ("Guide of Ogo", "奥戈向导"),
    ("Guide of Lost Souls", "迷途灵魂向导"),
    ("Scryer of the Lidless Eye", "无目之眼占卜者"),
    ("Monk of the Lidless Eye", "无目之眼僧侣"),
    ("Ascetic of the Lidless Eye", "无目之眼苦行僧"),
    ("One with the Void", "与虚空合一"),
    ("Born of Battle", "战生"),
    ("Born of Chaos", "混沌所生"),
    ("Celestial Body", "天体"),
    ("False Ally", "伪盟者"),
    ("Dark Emissary", "黑暗使者"),
    ("Dark Savant", "黑暗学者"),
    ("Dark Energy Shard", "黑暗能量碎片"),
    ("Energy Shard", "能量碎片"),
    ("Soul Gem", "灵魂宝石"),
    ("Soul Collector", "集魂者"),
    ("Soul Marshal", "灵魂元帅"),
    ("Lost Souls", "迷途灵魂"),
    ("Henge Queen", "环石女王"),
    ("Wild Queen", "荒野女王"),
    ("Askara Prince", "阿斯卡拉王子"),
    ("Askara of Fate", "命运阿斯卡拉"),
    ("Askara of Souls", "灵魂阿斯卡拉"),
    ("Askara of Fortune", "幸运阿斯卡拉"),
    ("Askara of Judgement", "审判阿斯卡拉"),
    ("Eternal Askara", "永恒阿斯卡拉"),
    ("Wandering Askara", "流浪阿斯卡拉"),
    ("Tower Askara", "高塔阿斯卡拉"),
    ("Daybreak Askara", "破晓阿斯卡拉"),
    ("Searing Askara", "灼热阿斯卡拉"),
    ("Divine Askara", "神圣阿斯卡拉"),
    ("Anointed Askara", "涂油阿斯卡拉"),
    ("Auspicious Askara", "吉兆阿斯卡拉"),
    ("Flanking Askara", "侧击阿斯卡拉"),
    ("Twofold Askara", "双重阿斯卡拉"),
    ("Shade Askara", "暗影阿斯卡拉"),
    ("Psyche Askara", "心灵阿斯卡拉"),
    ("Arha Initiate", "亚哈新兵"),
    ("Arha Templar", "亚哈圣殿武士"),
    ("Arha Medium", "亚哈灵媒"),
    ("Arha Mentor", "亚哈导师"),
    ("Arha Historian", "亚哈史官"),
    ("Arha Recruit", "亚哈新兵"),
    ("Arha Emissary", "亚哈使者"),
    ("Arha Sensei", "亚哈导师"),
    ("Lifebound Initiate", "生命新兵"),
    ("Lifebound Muse", "生命缪斯"),
    ("Lifebound Hero", "生命英雄"),
    ("Lifebound Remnant", "生命残响"),
    ("Mechana Initiate", "机械新兵"),
    ("Mechana Remnant", "机械残响"),
    ("Enlightened Remnant", "启迪残响"),
    ("Enlightened Hero", "启迪英雄"),
    ("Void Initiate", "虚空新兵"),
    ("Void Hero", "虚空英雄"),
    ("Void Remnant", "虚空残响"),
    ("Void Militia", "虚空民兵"),
    ("Void Avenger", "虚空复仇者"),
    ("Void Emissary", "虚空使者"),
    ("Heavy Infantry", "重装步兵"),
    ("Rocket Courier X-99", "火箭信使X-99"),
    ("Watchmaker's Altar", "制表师祭坛"),
    ("Hedron Link Device", "多面体连接装置"),
    ("Hedron Cannon", "多面体加农"),
    ("Great-Omen Raven", "大兆乌鸦"),
    ("Black Hole", "黑洞"),
    ("Project Alpha", "阿尔法计划"),
    ("Dimension Diver", "维度潜者"),
    ("Lunar Stag", "月鹿"),
    ("Deathseeker", "寻死者"),
    ("Ferromancer's Helper", "铁术师助手"),
    ("Socket Altar", "嵌口祭坛"),
    ("Battery Monk", "电池僧侣"),
    ("Fire Tyrant", "火焰暴君"),
    ("Wind Tyrant", "风之暴君"),
    ("Earth Tyrant", "大地暴君"),
    ("Sea Tyrant", "海中暴君"),
    ("Smoke Tyrant", "烟雾暴君"),
    ("Nightmare Tyrant", "梦魇暴君"),
    ("Twisted Tyrant", "扭曲暴君"),
    ("Hoarding Tyrant", "囤积暴君"),
    ("Valley Tyrant", "山谷暴君"),
    ("Dream Tyrant", "梦境暴君"),
    ("Iku, Valley Tyrant", "山谷暴君伊库"),
    ("Legendary Boon", "传奇恩赐"),
    ("Disciple of", "之徒·"),
    ("Scion of", "后裔·"),
    ("Avatar of", "化身·"),
    ("Temple of", "神殿·"),
    ("Boon:", "恩赐："),
    ("Legend:", "传奇："),
    ("Remnant of", "残响·"),
]

NAME_WORDS: list[tuple[str, str]] = [
    ("Askara", "阿斯卡拉"),
    ("Templar", "圣殿武士"),
    ("Initiate", "新兵"),
    ("Apprentice", "学徒"),
    ("Militia", "民兵"),
    ("Mystic", "秘教士"),
    ("Cultist", "邪教徒"),
    ("Fanatic", "狂信者"),
    ("Construct", "神器"),
    ("Monster", "怪物"),
    ("Heroes", "英雄"),
    ("Hero", "英雄"),
    ("Enlightened", "启迪"),
    ("Lifebound", "生命"),
    ("Mechana", "机械"),
    ("Hedron", "多面体"),
    ("Dreamscape", "梦境"),
    ("Delirium", "谵妄"),
    ("Dreambind", "梦缚"),
    ("Phantasm", "幻象"),
    ("Energize", "充能"),
    ("Empower", "赋力"),
    ("Transform", "转化"),
    ("Infest", "感染"),
    ("Serenity", "宁静"),
    ("Trophy", "战利品"),
    ("Fate", "天命"),
    ("Fates", "命运"),
    ("Honor", "荣誉"),
    ("Rune", "符文"),
    ("Runic", "符文"),
    ("Power", "战力"),
    ("Insight", "洞察"),
    ("Vigil", "祈夜"),
    ("Godslayer", "弑神者"),
    ("Mechana", "机械"),
    ("Monk", "僧侣"),
    ("Witch", "女巫"),
    ("Shaman", "萨满"),
    ("Priestess", "女祭司"),
    ("Priest", "祭司"),
    ("Druidess", "女德鲁伊"),
    ("Druids", "德鲁伊"),
    ("Druid", "德鲁伊"),
    ("Sage", "贤者"),
    ("Seer", "预言者"),
    ("Scribe", "书记"),
    ("Arbiter", "仲裁者"),
    ("Guardian", "守卫"),
    ("Warden", "守卫"),
    ("Keeper", "看守"),
    ("Hunter", "猎手"),
    ("Huntress", "女猎手"),
    ("Huntmaster", "猎主"),
    ("Assassin", "刺客"),
    ("Slayer", "斩杀者"),
    ("Emissary", "使者"),
    ("Messenger", "信使"),
    ("Courier", "信使"),
    ("Familiar", "使魔"),
    ("Tyrant", "暴君"),
    ("Dragon", "龙"),
    ("Wyrm", "巨虫"),
    ("Wurm", "巨虫"),
    ("Golem", "魔像"),
    ("Cannon", "加农"),
    ("Altar", "祭坛"),
    ("Staff", "法杖"),
    ("Blade", "刃"),
    ("Blades", "双刃"),
    ("Shield", "盾"),
    ("Helm", "盔"),
    ("Sword", "剑"),
    ("Axe", "斧"),
    ("Hammer", "锤"),
    ("Bow", "弓"),
    ("Star", "星"),
    ("Stars", "群星"),
    ("Soul", "灵魂"),
    ("Souls", "灵魂"),
    ("Horror", "恐魔"),
    ("Swarm", "虫群"),
    ("Drone", "无人机"),
    ("Weaver", "编织者"),
    ("Bane", "克星"),
    ("Lightbringer", "携光者"),
    ("Soulstealer", "窃魂者"),
    ("Shadowslayer", "斩影者"),
    ("Demonsbane", "恶魔克星"),
    ("Soulslayer", "斩魂者"),
    ("Voidmother", "虚空之母"),
    ("Ferromancer", "铁术师"),
    ("Ironmind", "铁心"),
    ("Worldbreaker", "碎界者"),
    ("Deathseeker", "寻死者"),
    ("Reclamax", "回收机"),
    ("Wrecklamax", "回收残机"),
    ("Gorph", "戈尔夫"),
    ("Serpentcall", "唤蛇"),
    ("Dandelion", "蒲公英"),
    ("Noxious", "毒害"),
    ("Fettered", "枷锁"),
    ("Vandal", "破坏"),
    ("Hoarding", "囤积"),
    ("Whelp", "幼龙"),
    ("Minotaur", "牛头人"),
    ("Shadowcaster", "影咏者"),
    ("Dreamer's", "梦者"),
    ("Glass", "玻璃"),
    ("Grease", "油污"),
    ("Trickster", "诡术师"),
    ("Flinger", "投掷者"),
    ("Cog", "齿轮"),
    ("Maw", "巨口"),
    ("Brazer", "铜匠"),
    ("Prodigal", "浪子"),
    ("Polaris", "北极星"),
    ("Demon", "恶魔"),
    ("Destiny", "命运"),
    ("Penumbral", "半影"),
    ("Umbral", "暗影"),
    ("Edge", "刃锋"),
    ("Everbloom", "永绽"),
    ("Siren", "海妖"),
    ("Snake", "蛇"),
    ("Honey", "蜜"),
    ("Alpha", "首领"),
    ("Unchained", "挣脱"),
    ("Cult", "邪教"),
    ("Rise", "崛起"),
    ("Personal", "私人"),
    ("Wormhole", "虫洞"),
    ("Nook", "角落"),
    ("Hound", "猎犬"),
    ("Abolisher", "废除者"),
    ("Aiyana", "艾雅娜"),
    ("Aiyana's", "艾雅娜的"),
    ("Canopic", "卡诺皮克"),
    ("Jar", "罐"),
    ("Starchild", "星之子"),
    ("Autobuilder", "自动建造机"),
    ("Treasures", "宝藏"),
    ("Treasure", "宝藏"),
    ("Study", "书房"),
    ("Elder", "长老"),
    ("Skeptic", "怀疑者"),
    ("Synchronizer", "同步者"),
    ("Granger", "农夫"),
    ("Machine", "机器"),
    ("Nemesis", "宿敌"),
    ("Weapon", "武器"),
    ("Nihilmancer", "虚无法师"),
    ("Lionheart", "狮心"),
    ("Elemental", "元素"),
    ("Adept", "能手"),
    ("Belthar", "贝尔萨"),
    ("Collector", "收集者"),
    ("Sabre", "军刀"),
    ("Moonlit", "月下"),
    ("Cackling", "狂笑"),
    ("Jackal", "豺狼"),
    ("Orb", "宝珠"),
    ("Nyx", "尼克斯"),
    ("Nyxian", "尼克斯"),
    ("Nyx's", "尼克斯的"),
    ("Elan", "埃兰"),
    ("Marshal", "元帅"),
    ("Recyclicrab", "循环蟹"),
    ("Driller", "钻机"),
    ("Deathsworn", "誓死"),
    ("Warrior", "战士"),
    ("Wandering", "流浪"),
    ("Kythis", "凯西斯"),
    ("Rebel", "反叛"),
    ("Godling", "神子"),
    ("Spark", "火花"),
    ("Sprayer", "喷射器"),
    ("Energy", "能量"),
    ("Medium", "灵媒"),
    ("Akam", "阿卡姆"),
    ("Genie", "灯神"),
    ("World", "世界"),
    ("Tree", "树"),
    ("Temple", "神殿"),
    ("Annihilation", "歼灭"),
    ("Acidic", "酸性"),
    ("Crawler", "爬行者"),
    ("Aaron", "亚伦"),
    ("Soulshaper", "塑魂者"),
    ("Avenger", "复仇者"),
    ("Growmites", "增生螨"),
    ("Pyromaniac", "纵火狂"),
    ("Beast", "野兽"),
    ("Cosmic", "宇宙"),
    ("Protocol", "协议"),
    ("Repurposer", "再造者"),
    ("Spider", "蜘蛛"),
    ("Wolf", "狼"),
    ("Acolyte", "侍僧"),
    ("Eclipse", "日食"),
    ("Reactor", "反应堆"),
    ("Shrine", "神龛"),
    ("Spirit", "精魂"),
    ("Merchant", "商人"),
    ("Omnicron", "全时者"),
    ("Mordant", "蚀骨"),
    ("Widow", "寡妇"),
    ("Vanquisher", "征服者"),
    ("Beacon", "信标"),
    ("Illiya", "伊利亚"),
    ("Demonborn", "魔生"),
    ("Foresight", "预见"),
    ("Monacle", "单片镜"),
    ("Oras", "奥拉斯"),
    ("Redeemer", "救赎者"),
    ("Tablet", "石板"),
    ("Dreamer", "梦者"),
    ("Magnet", "磁"),
    ("Temporal", "时光"),
    ("Eye", "之眼"),
    ("Portabillet", "便携弹"),
    ("Wildcall", "野性呼唤"),
    ("Righteous", "正义"),
    ("Terrus", "特鲁斯"),
    ("Paragon", "典范"),
    ("Strife", "争斗"),
    ("Serpent", "巨蛇"),
    ("Skyrocket", "冲天"),
    ("Reality", "现实"),
    ("Sculptor", "塑造者"),
    ("Lagoon", "潟湖"),
    ("Troll", "巨魔"),
    ("Loamspeaker", "沃土语者"),
    ("Demontrap", "捕魔阱"),
    ("Firestorm", "火暴"),
    ("Effigy", "偶像"),
    ("Tome", "典籍"),
    ("Erabus", "埃拉布斯"),
    ("Ulu", "乌鲁"),
    ("Prince", "王子"),
    ("Honiskrot", "霍尼斯克洛特"),
    ("Zeta", "泽塔"),
    ("Arsenal", "武库"),
    ("Cognition", "认知"),
    ("Deviant", "畸变"),
    ("Fiend", "邪魔"),
    ("Spiritcaster", "魂咏者"),
    ("Truth", "真理"),
    ("Seeker", "追寻者"),
    ("Starcaller", "唤星者"),
    ("Leotan", "莱奥坦"),
    ("Leotan's", "莱奥坦的"),
    ("Raging", "暴怒"),
    ("Ursine", "熊"),
    ("Protean", "多变"),
    ("Slug", "蛞蝓"),
    ("Prototype", "原型"),
    ("Twisted", "扭曲"),
    ("Muse", "缪斯"),
    ("Herald", "先驱"),
    ("Doom", "末日"),
    ("Darkwalker", "暗行者"),
    ("Vault", "宝库"),
    ("Sphinx", "狮身人面"),
    ("Monastic", "寺院"),
    ("Tutor", "导师"),
    ("Voidfeeder", "饲虚者"),
    ("Son", "之子"),
    ("Azerax", "阿泽拉克斯"),
    ("Chosen", "天选者"),
    ("Oxipede", "牛蜈"),
    ("Toric", "托里克"),
    ("Ascendant", "飞升者"),
    ("Nightmare", "梦魇"),
    ("Sentinel", "哨卫"),
    ("Moken", "莫肯"),
    ("Raven", "乌鸦"),
    ("Yolocryx", "约洛克瑞克斯"),
    ("Phasefiend", "相位邪魔"),
    ("Dredger", "挖掘者"),
    ("Shardfinder", "寻晶者"),
    ("Compass", "罗盘"),
    ("Tribesman", "部族人"),
    ("Champion", "冠军"),
    ("Webclaw", "网爪"),
    ("Lich", "巫妖"),
    ("Plunder", "掠夺"),
    ("Devil", "恶魔"),
    ("Gem-Eater", "噬晶"),
    ("Leprechaun", "小矮妖"),
    ("Scrabbler", "翻捡者"),
    ("Valiant", "勇毅"),
    ("Ascetic", "苦行僧"),
    ("Cacklecast", "狂笑施法"),
    ("Wretch", "可怜虫"),
    ("Charging", "充能"),
    ("Chamber", "室"),
    ("Yolothian", "约洛斯"),
    ("Monolith", "巨石"),
    ("Exiled", "流放者"),
    ("Crystalline", "水晶"),
    ("Voidsworn", "誓虚"),
    ("Gemcatcher", "捕晶者"),
    ("Veya", "维雅"),
    ("Handmaiden", "侍女"),
    ("Logos", "逻各斯"),
    ("Ritualist", "祭仪师"),
    ("Lost", "迷失"),
    ("Mosaic", "镶嵌"),
    ("Horn", "号角"),
    ("Dendris", "登德里斯"),
    ("Gladewyrm", "林间巨虫"),
    ("Scrabbling", "翻捡"),
    ("Squad", "小队"),
    ("Anointed", "涂油"),
    ("Replication", "复制"),
    ("Devoted", "虔诚"),
    ("Disciple", "门徒"),
    ("Riftwalker", "裂隙行者"),
    ("Riftwalker's", "裂隙行者的"),
    ("Otherworldly", "异界"),
    ("Mentor", "导师"),
    ("Jakeb", "杰克布"),
    ("Cobra", "眼镜蛇"),
    ("King", "王"),
    ("Chieftain", "酋长"),
    ("Wailing", "哀嚎"),
    ("Spectre", "幽灵"),
    ("Foundation", "根基"),
    ("Burrower", "钻地者"),
    ("Clutch", "掌握"),
    ("Darkness", "黑暗"),
    ("Zero", "零"),
    ("Point", "点"),
    ("Air", "空中"),
    ("Support", "支援"),
    ("Squadron", "中队"),
    ("Sadistic", "虐杀"),
    ("Giant", "巨人"),
    ("Delver", "深掘者"),
    ("Timestream", "时流"),
    ("Remus", "雷穆斯"),
    ("Pack", "兽群"),
    ("Wreath", "花环"),
    ("Workshop", "工坊"),
    ("Gargoyle", "石像鬼"),
    ("Voidforged", "虚空锻"),
    ("Paladin", "圣骑士"),
    ("Wild", "荒野"),
    ("Clique", "小圈子"),
    ("Exemplar", "典范"),
    ("Wildgear", "野性齿轮"),
    ("Potential", "潜能"),
    ("Eternal", "永恒"),
    ("Sower", "播种者"),
    ("Discontent", "不满"),
    ("Shadow", "暗影"),
    ("Stalker", "潜行者"),
    ("Betrayal", "背叛"),
    ("Watchtower", "瞭望塔"),
    ("Upgrade", "升级"),
    ("Foundry", "铸造厂"),
    ("Deathbound", "缚死"),
    ("Canon", "圣典"),
    ("Defense", "防御"),
    ("Generator", "发生器"),
    ("Vir", "维尔"),
    ("Ephemeral", "昙花"),
    ("Guru", "古鲁"),
    ("Adayu", "阿达尤"),
    ("Serene", "宁静"),
    ("Tormented", "受折磨"),
    ("Borderland", "边地"),
    ("Mercenary", "佣兵"),
    ("Journeyman", "旅者"),
    ("Outrider", "先驱骑手"),
    ("Nihilist", "虚无者"),
    ("Alset", "阿尔塞特"),
    ("Savant", "学者"),
    ("Unmaker", "解构者"),
    ("Snapdragon", "金鱼草"),
    ("Terrorizing", "威吓"),
    ("Discovery", "发现"),
    ("Matron", "主母"),
    ("Laboratory", "实验室"),
    ("Secluded", "隐秘"),
    ("Verdant", "翠绿"),
    ("Crown", "冠冕"),
    ("Mantra", "真言"),
    ("Sight", "视界"),
    ("Deathdealer", "死神"),
    ("Noble", "贵族"),
    ("Animus", "魂魄"),
    ("Forgotten", "遗忘"),
    ("Scripture", "经文"),
    ("Neophyte", "新入门者"),
    ("Deathfinder", "寻死者"),
    ("Bargain", "交易"),
    ("Sadranis", "萨德拉尼斯"),
    ("Savant", "学者"),
    ("Renewal", "更新"),
    ("Thorned", "棘刺"),
    ("Charger", "冲锋者"),
    ("Flytrap", "捕蝇草"),
    ("Daybreak", "破晓"),
    ("Morbid", "病态"),
    ("Surya", "苏尔亚"),
    ("Light's", "光明的"),
    ("Light", "光"),
    ("Maniacal", "狂乱"),
    ("Crusher", "粉碎者"),
    ("Prospector", "探矿者"),
    ("Scout", "斥候"),
    ("Xeron", "泽伦"),
    ("Xeron's", "泽伦的"),
    ("Lord", "领主"),
    ("Deofol", "迪奥福尔"),
    ("Aranyx", "阿兰尼克斯"),
    ("Glutton", "贪食者"),
    ("Riftwatch", "裂隙守望"),
    ("Turret", "炮塔"),
    ("Sting", "毒刺"),
    ("Library", "图书馆"),
    ("Rejected", "废弃"),
    ("Betrayed", "被弃"),
    ("Gnome", "侏儒"),
    ("Repairbot", "修理机"),
    ("Surge", "浪涌"),
    ("Protector", "保护者"),
    ("Riftdrake", "裂隙龙兽"),
    ("Riftgate", "裂隙门"),
    ("Conjuror", "咒术师"),
    ("Bug", "虫"),
    ("Ogo", "奥戈"),
    ("Ogo's", "奥戈的"),
    ("Rebirth", "重生"),
    ("Rider", "骑手"),
    ("Shepherd", "牧者"),
    ("Genesis", "创世"),
    ("Capsule", "舱"),
    ("Clockwork", "发条"),
    ("Sentry", "哨兵"),
    ("Exhaust", "废气"),
    ("Lurker", "潜伏者"),
    ("Rootscryer", "根卜者"),
    ("Canopy", "树冠"),
    ("Sanctuary", "圣所"),
    ("Premonition", "预感"),
    ("Bell", "钟"),
    ("False", "虚假"),
    ("Circle", "环"),
    ("Moonveil", "月纱"),
    ("Leader", "首领"),
    ("Dawn", "黎明"),
    ("Undaunted", "无畏"),
    ("Overhaul", "大修"),
    ("Cleric", "神职者"),
    ("Austere", "严苛"),
    ("Nairi", "奈莉"),
    ("Nairi's", "奈莉的"),
    ("Queen", "女王"),
    ("Conversion", "转化"),
    ("Port", "端口"),
    ("Plasma", "等离子"),
    ("Corrupted", "腐化"),
    ("Kor", "科尔"),
    ("Adam", "亚当"),
    ("Builder", "建造者"),
    ("Starlight", "星光"),
    ("Sanctum", "圣所"),
    ("Dhartha", "达萨"),
    ("Dhartha's", "达萨的"),
    ("Master", "大师"),
    ("Days", "往日"),
    ("Past", "过去"),
    ("Resolve", "决意"),
    ("Loa", "洛阿"),
    ("Sleeping", "沉睡"),
    ("Tidestalker", "潮潜者"),
    ("Deluding", "欺瞒"),
    ("Djinn", "灯神"),
    ("Aura", "灵光"),
    ("Fen", "沼"),
    ("Imaginative", "想象"),
    ("Dreamwillow", "梦柳"),
    ("Unbound", "解缚"),
    ("Berserker", "狂战"),
    ("Planar", "位面"),
    ("Aperture", "孔径"),
    ("Puppetmaster", "傀儡师"),
    ("Brainstorm", "头脑风暴"),
    ("Wicked", "邪"),
    ("End", "终结"),
    ("Fear", "恐惧"),
    ("Wielder", "持有者"),
    ("Garden", "园丁"),
    ("Attendant", "侍从"),
    ("Inventor", "发明家"),
    ("Fairy", "妖精"),
    ("Verdagris", "维达格里斯"),
    ("Fleeting", "飞逝"),
    ("Hope", "希望"),
    ("Lunar", "月"),
    ("Pasythea", "帕西提亚"),
    ("Pasythea's", "帕西提亚的"),
    ("Aegis", "神盾"),
    ("Nocturnal", "夜行"),
    ("Caustic", "腐蚀"),
    ("Conjurer", "咒术师"),
    ("Alluring", "魅惑"),
    ("Censer", "香炉"),
    ("Armistice", "停战"),
    ("Inquarry", "采石"),
    ("Hydra", "九头蛇"),
    ("Trinket", "饰品"),
    ("Harpy", "鹰身女妖"),
    ("Call", "呼唤"),
    ("Technological", "科技"),
    ("Leap", "跃进"),
    ("Hulking", "庞大"),
    ("Crab", "蟹"),
    ("Harvester", "收割者"),
    ("Frenzy", "狂乱"),
    ("Reverie", "幻想"),
    ("Embrace", "拥抱"),
    ("Engulfing", "吞噬"),
    ("Kraken", "克拉肯"),
    ("Blessing", "祝福"),
    ("Respite", "喘息"),
    ("Cetra", "塞特拉"),
    ("Cetra's", "塞特拉的"),
    ("Rust", "锈"),
    ("Gremlin", "小妖"),
    ("Gremlins", "小妖们"),
    ("Raka", "拉卡"),
    ("Dreamtender", "守梦者"),
    ("Lab", "实验室"),
    ("Nilus", "尼卢斯"),
    ("Despair", "绝望"),
    ("Order", "秩序"),
    ("Gear", "齿轮"),
    ("Chaos", "混沌"),
    ("Test", "试炼"),
    ("Faith", "信仰"),
    ("Stalk", "潜行"),
    ("Shadows", "暗影"),
    ("Loam", "沃土"),
    ("Summoner", "召唤师"),
    ("Synapse", "突触"),
    ("Spire", "尖塔"),
    ("Tank", "坦克"),
    ("Detector", "探测器"),
    ("Yggdrasil", "世界树"),
    ("Dreamshaper", "塑梦者"),
    ("Jesse", "杰西"),
    ("Chronicle", "编年史"),
    ("Ward", "守护"),
    ("Hatchling", "幼体"),
    ("Deluxe", "豪华"),
    ("Capacitor", "电容"),
    ("Dragoon", "龙骑兵"),
    ("Bringer", "带来者"),
    ("Dreamkiller", "弑梦者"),
    ("Askaran", "阿斯卡拉"),
    ("Armor", "甲"),
    ("Thieving", "偷窃"),
    ("Gryphon", "狮鹫"),
    ("Auspicious", "吉兆"),
    ("Aklys", "阿克里斯"),
    ("Scourge", "灾祸"),
    ("Solar", "日"),
    ("Marsh", "沼泽"),
    ("Ranger", "游侠"),
    ("Sureshot", "神射"),
    ("Tracker", "追踪者"),
    ("Searing", "灼热"),
    ("Flare", "闪光"),
    ("Illuminator", "照明者"),
    ("Lieutenant", "副官"),
    ("Duros", "杜洛斯"),
    ("Inspired", "受启"),
    ("Deceitful", "欺诈"),
    ("Ghoul", "食尸鬼"),
    ("Emberwing", "烬翼"),
    ("Moth", "蛾"),
    ("Gladiator", "角斗士"),
    ("Scavenger", "拾荒者"),
    ("Ants", "蚁群"),
    ("Isha", "伊莎"),
    ("Pursuer", "追猎者"),
    ("Chanter", "咏者"),
    ("Historian", "史官"),
    ("Legion", "军团"),
    ("Dread", "恐惧"),
    ("Converter", "转化者"),
    ("Viper", "毒蛇"),
    ("Cavern", "洞穴"),
    ("Creeper", "爬行者"),
    ("Twilight", "暮光"),
    ("Shade", "暗影"),
    ("Wartorn", "战创"),
    ("Pillar", "柱"),
    ("Vyrak", "维拉卡"),
    ("First", "初代"),
    ("Deadeye", "死眼"),
    ("Dogs", "犬"),
    ("War", "战争"),
    ("Ta'hyr", "塔希尔"),
    ("Sun", "太阳"),
    ("Sunstreak", "日迹"),
    ("Luro", "卢罗"),
    ("Shardwing", "晶翼"),
    ("Beetle", "甲虫"),
    ("Outpost", "前哨"),
    ("Earthmender", "愈地者"),
    ("Pura", "普拉"),
    ("Madness'", "疯狂的"),
    ("Processing", "处理"),
    ("Hub", "枢纽"),
    ("Radiant", "辉耀"),
    ("Aspirant", "追求者"),
    ("Directive", "指令"),
    ("Deluge", "洪水"),
    ("Sonny", "桑尼"),
    ("Lightwielder", "持光者"),
    ("Reysa", "雷萨"),
    ("Reysa's", "雷萨的"),
    ("Trial", "试炼"),
    ("Yur", "尤尔"),
    ("Keen-eyed", "锐眼"),
    ("Keen", "锐"),
    ("eyed", "眼"),
    ("Forgemother", "锻母"),
    ("Conduit", "导管"),
    ("Yuk", "尤克"),
    ("Tribe", "部落"),
    ("Eek", "伊克"),
    ("Static", "静电"),
    ("Tectonic", "地壳"),
    ("Thrasher", "鞭笞者"),
    ("Unspeakable", "不可名状"),
    ("Ulan", "乌兰"),
    ("Ulan's", "乌兰的"),
    ("Nom", "诺姆"),
    ("Piercing", "贯穿"),
    ("Bramble", "荆棘"),
    ("Wildbark", "野树皮"),
    ("Mail", "甲胄"),
    ("Ally", "盟友"),
    ("Brother", "修士"),
    ("Laias", "莱亚斯"),
    ("Innovative", "创新"),
    ("Outcast", "放逐者"),
    ("Fist", "拳"),
    ("Venom", "毒液"),
    ("Wildfire", "野火"),
    ("Whirlwind", "旋风"),
    ("Oblivion", "湮灭"),
    ("Blossoms", "花"),
    ("Projector", "投射器"),
    ("Cell", "牢房"),
    ("Block", "区"),
    ("Voidrift", "虚空裂隙"),
    ("Deranged", "发狂"),
    ("Blast", "爆破"),
    ("Goggles", "护目镜"),
    ("Sister", "姐妹"),
    ("Wind", "风"),
    ("Water", "水"),
    ("Iron", "铁"),
    ("Grand-Arbiter", "大仲裁者"),
    ("Grand", "大"),
    ("Todd", "托德"),
    ("Patient", "耐心"),
    ("Flourishing", "繁盛"),
    ("Bam", "巴姆"),
    ("Hearthglow", "炉辉"),
    ("Kiri", "基莉"),
    ("Meadow", "草地"),
    ("Qadim", "卡迪姆"),
    ("Cheerful", "欢快"),
    ("Consort", "伴侣"),
    ("Life", "生命"),
    ("Death", "死亡"),
    ("Immortality", "不朽"),
    ("Hurras", "胡拉斯"),
    ("Sea's", "海之"),
    ("Sea", "海"),
    ("Fury", "狂怒"),
    ("Excavator", "挖掘机"),
    ("Pilot", "驾驶员"),
    ("Iku", "伊库"),
    ("Iku's", "伊库的"),
    ("Minions", "爪牙"),
    ("Marius", "马里乌斯"),
    ("Endbringer", "终末使者"),
    ("Jora", "乔拉"),
    ("Kan'zir", "坎齐尔"),
    ("Ravager", "毁灭者"),
    ("Caretaker", "看护者"),
    ("Zahral", "扎拉尔"),
    ("Burial", "埋葬"),
    ("Sirewood", "父木"),
    ("Blind", "盲"),
    ("Reckless", "鲁莽"),
    ("Mutated", "突变"),
    ("Hellfrost", "狱霜"),
    ("Imps", "小恶魔"),
    ("Stormsmith", "风暴匠"),
    ("Anvil", "铁砧"),
    ("Starved", "饥馑"),
    ("Abomination", "憎恶"),
    ("Crypt", "地穴"),
    ("Salvagemaster", "打捞大师"),
    ("Mila", "米拉"),
    ("Flanking", "侧击"),
    ("Grave", "坟墓"),
    ("Isla", "伊斯拉"),
    ("Prodigy", "神童"),
    ("Tyranyx", "泰兰尼克斯"),
    ("Pillager", "劫掠者"),
    ("Silenced", "噤声"),
    ("Prophet", "先知"),
    ("Resourceful", "机智"),
    ("Trader", "商人"),
    ("Forgemaster's", "锻主的"),
    ("Suit", "套装"),
    ("Soulsnare", "魂阱"),
    ("Excavation", "发掘"),
    ("Spiteful", "怨毒"),
    ("Asalas", "阿萨拉斯"),
    ("Impaler", "穿刺者"),
    ("Sacred", "神圣"),
    ("Pot", "罐"),
    ("Shadowridge", "影脊"),
    ("Alosyan", "阿洛西亚"),
    ("Ominous", "不祥"),
    ("Augur", "占兆者"),
    ("Randall", "兰德尔"),
    ("Dirge", "挽歌"),
    ("Siegemaster's", "攻城主的"),
    ("Ram", "攻城槌"),
    ("Pathfinder's", "探路者的"),
    ("Totem", "图腾"),
    ("Ancient", "上古"),
    ("Stag", "鹿"),
    ("Jubilant", "欢庆"),
    ("Secrets", "秘密"),
    ("Tuskrider", "牙骑手"),
    ("Steelweaver", "织钢者"),
    ("Mechamonk", "机械僧"),
    ("Dream", "梦"),
    ("Emma", "艾玛"),
    ("Emma's", "艾玛的"),
    ("Ironheart", "铁之心"),
    ("Knight", "骑士"),
    ("Evvy", "艾薇"),
    ("Gift", "馈赠"),
    ("Vineweaver", "织藤者"),
    ("Karion", "卡里昂"),
    ("Glover", "格洛弗"),
    ("Titan", "泰坦"),
    ("Divine", "神圣"),
    ("Salvage", "打捞"),
    ("Yard", "场"),
    ("Zis", "齐斯"),
    ("Dreamreaper", "刈梦者"),
    ("Pixies", "小仙"),
    ("Pixie", "小仙"),
    ("Dreadmare", "惧马"),
    ("Mammoth", "巨"),
    ("Chemist", "药剂师"),
    ("Bleaktoad", "荒蟾"),
    ("Dryad", "树灵"),
    ("Pups", "幼崽"),
    ("Nilhammer", "虚无锤"),
    ("Nymph", "宁芙"),
    ("Circlet", "头环"),
    ("Scrapbot", "废料机"),
    ("Scrapper", "拆解者"),
    ("Naka", "纳卡"),
    ("Shadeborn", "影生"),
    ("Darktome", "暗典"),
    ("Librarian", "图书管理员"),
    ("Voidspeaker", "虚空语者"),
    ("Voidrager", "虚空狂怒者"),
    ("Dealer", "交易者"),
    ("Torment", "折磨"),
    ("Legionary", "军团兵"),
    ("Pollen", "花粉"),
    ("Oak", "橡"),
    ("Inferna", "炼狱"),
    ("General", "将军"),
    ("Bearer", "持有者"),
    ("Diviner", "占卜者"),
    ("Eater", "吞噬者"),
    ("Channeler", "引导者"),
    ("Curator", "策展者"),
    ("Aether", "以太"),
    ("Aetherspring", "以太泉"),
    ("Aethermourne", "以太哀歌"),
    ("Destroyer's", "毁灭者的"),
    ("Gate", "门"),
    ("Tollmaster", "税吏"),
    ("Ky'lek", "凯莱克"),
    ("Portal", "传送门"),
    ("David", "大卫"),
    ("Prophetic", "预言"),
    ("Nova", "诺娃"),
    ("Ethereal", "空灵"),
    ("Defender", "防御者"),
    ("Forrest", "福雷斯特"),
    ("Beastwarden", "兽卫"),
    ("Matriarch", "女族长"),
    ("Tinkering", "摆弄"),
    ("Seed", "种子"),
    ("Chaotic", "混沌"),
    ("Puggageddon", "巴哥末日"),
    ("Faerie", "仙灵"),
    ("Commander", "指挥官"),
    ("Psyche", "心灵"),
    ("Corite", "刚玉"),
    ("Mechanadon", "机械兽"),
    ("Invokist", "祈唤师"),
    ("Zinta", "辛塔"),
    ("Zinta's", "辛塔的"),
    ("Bracers", "护腕"),
    ("Blackwatch", "黑卫"),
    ("Katana", "刀"),
    ("Cutlass", "弯刀"),
    ("Psyonic", "心灵"),
    ("Anchor", "锚"),
    ("Entrophantasm", "熵幻象"),
    ("Voidcycler", "虚空循环器"),
    ("Controlsmith", "控术匠"),
    ("Dreamscarred", "梦痕"),
    ("Teletransmitter", "远传器"),
    ("Dreadmage", "恐惧法师"),
    ("Mechannon", "机加农"),
    ("Blueprint", "蓝图"),
    ("Nightmarauders", "梦魇掠夺者"),
    ("River", "河"),
    ("Reaper", "收割者"),
    ("Rakar", "拉卡尔"),
    ("Corrupt", "腐化"),
    ("Caaro", "卡罗"),
    ("Desert", "沙漠"),
    ("Breaker", "破碎者"),
    ("Redeemed", "救赎者"),
    ("Scimitar", "弯刀"),
    ("Lychan", "狼化"),
    ("Warprogue", "扭曲游荡者"),
    ("Terminites", "终末蚁"),
    ("Dreamwalker", "梦行者"),
    ("Nilia", "尼莉亚"),
    ("Shattered", "破碎"),
    ("Bomber", "投弹者"),
    ("Wereboar", "野猪人"),
    ("Warpdruid", "扭曲德鲁伊"),
    ("Amathyst", "紫晶"),
    ("Artificers", "神器师"),
    ("Gearseer", "齿轮预言者"),
    ("Dreamseeker", "寻梦者"),
    ("Azurite", "蓝铜"),
    ("Bounty", "丰饶"),
    ("Obfusca", "朦胧"),
    ("Mace", "锤矛"),
    ("Green", "绿"),
    ("Spritelings", "小精灵"),
    ("Disciples", "门徒们"),
    ("Dimension", "维度"),
    ("Diver", "潜者"),
    ("Combustion", "燃烧"),
    ("Idol", "偶像"),
    ("Retreat", "隐修处"),
    ("Hectic", "忙乱"),
    ("Sordid", "污秽"),
    ("Asp", "蝮蛇"),
    ("Vaultbreaker", "破库"),
    ("Ravenous", "贪婪"),
    ("Elite", "精锐"),
    ("Weeper", "哀泣者"),
    ("Bazu", "巴祖"),
    ("Scorn", "轻蔑"),
    ("Project", "计划"),
    ("Hole", "洞"),
    ("Helper", "助手"),
    ("Battery", "电池"),
    ("Socket", "嵌口"),
    ("Fire", "火焰"),
    ("Doom", "末日"),
    ("Dark", "黑暗"),
    ("Rising", "崛起"),
    ("Stone", "石"),
    ("Lunar", "月"),
    ("Great", "大"),
    ("Omen", "预兆"),
    ("Mark", "型号"),
    ("Duke", "公爵"),
    ("Lies", "谎言"),
    ("Queen", "女王"),
    ("Watch", "卫队"),
    ("Emri", "艾姆瑞"),
    ("Emri's", "艾姆瑞的"),
    ("Oziah", "奥齐亚"),
    ("Oziah's", "奥齐亚的"),
    ("Euloth", "尤洛斯"),
    ("Naira", "奈拉"),
    ("Naka", "纳卡"),
    ("Mecha", "机甲"),
    ("Remnant", "残响"),
    ("Boon", "恩赐"),
    ("Legend", "传奇"),
    ("Legendary", "传奇"),
    ("Recruit", "新兵"),
    ("Judgement", "审判"),
    ("Pathseeker", "寻路者"),
    ("Sensei", "导师"),
    ("Mountain", "山"),
    ("Vaya", "瓦娅"),
    ("Mycelial", "菌丝"),
    ("Mage", "法师"),
    ("Mushroom", "蘑菇"),
    ("Fang", "牙"),
    ("Forest", "森林"),
    ("Snowstrider", "踏雪者"),
    ("Lycan", "狼化人"),
    ("Turtler", "龟商"),
    ("Landis'", "兰迪斯的"),
    ("Potions", "药剂"),
    ("Pies", "馅饼"),
    ("Sablespark", "黑火花"),
    ("Sisters", "姐妹"),
    ("Dreamscrape", "刮梦"),
    ("Korpse", "尸科尔"),
    ("Maker", "制造者"),
    ("Mechannihilator", "机歼灭者"),
    ("Engine", "引擎"),
    ("Mechaphoenix", "机凤凰"),
    ("Bombcrafter", "炸弹匠"),
    ("Feather", "羽"),
    ("Mender", "修复者"),
    ("Raiyna", "蕾娜"),
    ("Riftclaw", "裂隙爪"),
    ("Claws", "爪"),
    ("Deoful", "迪奥福尔"),
    ("Hurricane", "飓风"),
    ("Warlock", "术士"),
    ("Correction", "校正"),
    ("Creation", "造物"),
    ("Seven", "七"),
    ("Hellstring", "狱弦"),
    ("MarrowWyrm", "髓虫"),
    ("Malevolence", "恶意"),
    ("Psychic", "心灵"),
    ("Amulet", "护符"),
    ("Ninja", "忍者"),
    ("Fae", "仙灵"),
    ("Chrome", "铬"),
    ("Fallen", "堕落者"),
    ("Psionic", "灵能"),
    ("Void", "虚空"),
    ("Dream", "梦"),
    ("Scrap", "废料"),
    ("Shadow", "暗影"),
    ("Spirit", "精魂"),
    ("Guide", "向导"),
    ("Hunter", "猎手"),
    ("Temple", "神殿"),
    ("Circle", "环"),
    ("Soul", "灵魂"),
    ("Dark", "黑暗"),
    ("Master", "大师"),
    ("Stone", "石"),
    ("Chaos", "混沌"),
    ("Scout", "斥候"),
    ("Verdant", "翠绿"),
    ("Sentry", "哨兵"),
    ("Aspirant", "追求者"),
    ("Sage", "贤者"),
    ("Ironheart", "铁之心"),
    ("Blueprint", "蓝图"),
    ("Workshop", "工坊"),
    ("Muse", "缪斯"),
    ("Shard", "碎片"),
    ("Nightmare", "梦魇"),
    ("Scion", "后裔"),
    ("Ritualist", "祭仪师"),
    ("Spire", "尖塔"),
    ("Hope", "希望"),
    ("Assassin", "刺客"),
    ("Eternal", "永恒"),
    ("Clique", "小圈子"),
    ("Stalker", "潜行者"),
    ("Dragon", "龙"),
    ("Serene", "宁静"),
    ("Warrior", "战士"),
    ("Chosen", "天选者"),
    ("Spirit", "精魂"),
    ("Burrower", "钻地者"),
    ("Avatar", "化身"),
    ("Messenger", "信使"),
    ("Militia", "民兵"),
    ("Machine", "机器"),
    ("Retreat", "隐修处"),
    ("Combustion", "燃烧"),
    ("Idol", "偶像"),
    ("Project", "计划"),
    ("Diver", "潜者"),
    ("Adept", "能手"),
    ("Maw", "巨口"),
    ("Edge", "刃锋"),
    ("Cult", "邪教"),
    ("Spark", "火花"),
    ("Mentor", "导师"),
    ("Fiend", "邪魔"),
    ("Savant", "学者"),
    ("Laboratory", "实验室"),
    ("Darkness", "黑暗"),
    ("Canopy", "树冠"),
    ("Berserker", "狂战"),
    ("Despair", "绝望"),
    ("Ashes", "灰烬"),
    ("Dust", "尘土"),
    ("Curator", "策展者"),
    ("Gate", "门"),
    ("Defender", "防御者"),
    ("Potential", "潜能"),
    ("Born", "诞生"),
    ("World", "世界"),
    ("Resolve", "决意"),
    ("Attendant", "侍从"),
    ("Ranger", "游侠"),
    ("Tracker", "追踪者"),
    ("Foundry", "铸造厂"),
    ("Watchtower", "瞭望塔"),
    ("Gladiator", "角斗士"),
    ("Conjurer", "咒术师"),
    ("Beetle", "甲虫"),
    ("Scavenger", "拾荒者"),
    ("Cavern", "洞穴"),
    ("Outpost", "前哨"),
    ("Crusher", "粉碎者"),
    ("Embrace", "拥抱"),
    ("Fist", "拳"),
    ("Prodigy", "神童"),
    ("Excavator", "挖掘机"),
    ("Repairbot", "修理机"),
    ("Beacon", "信标"),
    ("Lurker", "潜伏者"),
    ("Widow", "寡妇"),
    ("Shield", "盾"),
    ("Nihil", "虚无"),
    ("Eater", "吞噬者"),
    ("Titan", "泰坦"),
    ("Beast", "野兽"),
    ("Dreamer", "梦者"),
    ("Tablet", "石板"),
    ("Merchant", "商人"),
    ("Fallen", "堕落者"),
    ("Rocket", "火箭"),
    ("Lies", "谎言"),
    ("Omen", "预兆"),
    ("Duke", "公爵"),
    ("Runic", "符文"),
    ("Unbound", "解缚"),
    ("Rebel", "反叛"),
    ("Godling", "神子"),
    ("Lidless", "无目"),
    ("Prototype", "原型"),
    ("Vault", "宝库"),
    ("Toric", "托里克"),
    ("Mantra", "真言"),
    ("Sight", "视界"),
    ("Pack", "兽群"),
    ("Sower", "播种者"),
    ("Flytrap", "捕蝇草"),
    ("Dreamwillow", "梦柳"),
    ("Djinn", "灯神"),
    ("Fatality", "致命"),
    ("Channeler", "引导者"),
    ("Portal", "传送门"),
    ("Seed", "种子"),
    ("Twilight", "暮光"),
    ("Pillar", "柱"),
    ("Sun", "太阳"),
    ("Searing", "灼热"),
    ("Historian", "史官"),
    ("Marsh", "沼泽"),
    ("Chanter", "咏者"),
    ("Map", "地图"),
    ("Solar", "日"),
    ("Illuminator", "照明者"),
    ("Flare", "闪光"),
    ("Rescuebot", "救援机"),
    ("Converter", "转化者"),
    ("Dogs", "犬"),
    ("Deadeye", "死眼"),
    ("Dread", "恐惧"),
    ("Wartorn", "战创"),
    ("Pursuer", "追猎者"),
    ("Deceitful", "欺诈"),
    ("Ghoul", "食尸鬼"),
    ("Ants", "蚁群"),
    ("Moth", "蛾"),
    ("Creeper", "爬行者"),
    ("Viper", "毒蛇"),
    ("Lieutenant", "副官"),
    ("Legion", "军团"),
    ("Scourge", "灾祸"),
    ("Radiant", "辉耀"),
    ("Water", "水"),
    ("Sister", "姐妹"),
    ("Outcast", "放逐者"),
    ("Thunder", "雷"),
    ("Whirlwind", "旋风"),
    ("Lightwielder", "持光者"),
    ("Piercing", "贯穿"),
    ("Celestial", "天体"),
    ("Body", "体"),
    ("Thicket", "灌木丛"),
    ("Flourishing", "繁盛"),
    ("Meadow", "草地"),
    ("Hearthglow", "炉辉"),
    ("Earthmender", "愈地者"),
    ("Wildbark", "野树皮"),
    ("Mail", "甲胄"),
    ("Heroes", "英雄"),
    ("Forgemother", "锻母"),
    ("Innovative", "创新"),
    ("Projector", "投射器"),
    ("Processing", "处理"),
    ("Hub", "枢纽"),
    ("Blast", "爆破"),
    ("Goggles", "护目镜"),
    ("Cell", "牢房"),
    ("Block", "区"),
    ("Battle", "战斗"),
    ("Patient", "耐心"),
    ("Venom", "毒液"),
    ("Priestess", "女祭司"),
    ("Grand", "大"),
    ("Madness'", "疯狂的"),
    ("Oblivion", "湮灭"),
    ("Blossoms", "花"),
    ("Ally", "盟友"),
    ("Nom", "诺姆"),
    ("Bam", "巴姆"),
    ("Bramble", "荆棘"),
    ("Wildfire", "野火"),
    ("Unspeakable", "不可名状"),
    ("Tectonic", "地壳"),
    ("Thrasher", "鞭笞者"),
    ("Static", "静电"),
    ("Eek", "伊克"),
    ("Deluge", "洪水"),
    ("Life", "生命"),
    ("Immortality", "不朽"),
    ("Blind", "盲"),
    ("Ominous", "不祥"),
    ("Augur", "占兆者"),
    ("Jubilant", "欢庆"),
    ("Secrets", "秘密"),
    ("Flanking", "侧击"),
    ("Sacred", "神圣"),
    ("Pot", "罐"),
    ("Ancient", "上古"),
    ("Cheerful", "欢快"),
    ("Consort", "伴侣"),
    ("Alosyan", "阿洛西亚"),
    ("Sirewood", "父木"),
    ("Burial", "埋葬"),
    ("Caretaker", "看护者"),
    ("Impaler", "穿刺者"),
    ("Pathfinder's", "探路者的"),
    ("Totem", "图腾"),
    ("Resourceful", "机智"),
    ("Trader", "商人"),
    ("Pilot", "驾驶员"),
    ("Salvagemaster", "打捞大师"),
    ("Forgemaster's", "锻主的"),
    ("Suit", "套装"),
    ("Stormsmith", "风暴匠"),
    ("Anvil", "铁砧"),
    ("Siegemaster's", "攻城主的"),
    ("Ram", "攻城槌"),
    ("Pillager", "劫掠者"),
    ("Reckless", "鲁莽"),
    ("Shadowridge", "影脊"),
    ("Spiteful", "怨毒"),
    ("Excavation", "发掘"),
    ("Soulsnare", "魂阱"),
    ("Silenced", "噤声"),
    ("Prophet", "先知"),
    ("Endbringer", "终末使者"),
    ("Dirge", "挽歌"),
    ("Hellfrost", "狱霜"),
    ("Imps", "小恶魔"),
    ("Crypt", "地穴"),
    ("Starved", "饥馑"),
    ("Abomination", "憎恶"),
    ("Minions", "爪牙"),
    ("Mutated", "突变"),
    ("Ravager", "毁灭者"),
    ("Fury", "狂怒"),
    ("Valley", "山谷"),
    ("Diviner", "占卜者"),
    ("Knight", "骑士"),
    ("Dealer", "交易者"),
    ("General", "将军"),
    ("Divine", "神圣"),
    ("Nymph", "宁芙"),
    ("Dryad", "树灵"),
    ("Pollen", "花粉"),
    ("Pixie", "小仙"),
    ("Tuskrider", "牙骑手"),
    ("Vineweaver", "织藤者"),
    ("Gift", "馈赠"),
    ("Steelweaver", "织钢者"),
    ("Scrapbot", "废料机"),
    ("Scrapper", "拆解者"),
    ("Inferna", "炼狱"),
    ("Salvage", "打捞"),
    ("Yard", "场"),
    ("Mechamonk", "机械僧"),
    ("Chemist", "药剂师"),
    ("Voidrager", "虚空狂怒者"),
    ("Bearer", "持有者"),
    ("Voidspeaker", "虚空语者"),
    ("Darktome", "暗典"),
    ("Librarian", "图书管理员"),
    ("Shadeborn", "影生"),
    ("Circlet", "头环"),
    ("Nilhammer", "虚无锤"),
    ("Pups", "幼崽"),
    ("Pixies", "小仙"),
    ("Mammoth", "巨"),
    ("Bleaktoad", "荒蟾"),
    ("Dreadmare", "惧马"),
    ("Oak", "橡"),
    ("Dreamreaper", "刈梦者"),
    ("Torment", "折磨"),
    ("Legionary", "军团兵"),
    ("Dreamseeker", "寻梦者"),
    ("Redeemed", "救赎者"),
    ("Cutlass", "弯刀"),
    ("Katana", "刀"),
    ("Mace", "锤矛"),
    ("Scimitar", "弯刀"),
    ("Dreamwalker", "梦行者"),
    ("Disciples", "门徒们"),
    ("Azurite", "蓝铜"),
    ("Channeler", "引导者"),
    ("Psyche", "心灵"),
    ("Anchor", "锚"),
    ("Entrophantasm", "熵幻象"),
    ("Dreamscarred", "梦痕"),
    ("Faerie", "仙灵"),
    ("Commander", "指挥官"),
    ("Spritelings", "小精灵"),
    ("Wereboar", "野猪人"),
    ("Oaken", "橡木"),
    ("Bounty", "丰饶"),
    ("Corite", "刚玉"),
    ("Mechanadon", "机械兽"),
    ("Controlsmith", "控术匠"),
    ("Artificers", "神器师"),
    ("Gearseer", "齿轮预言者"),
    ("Amathyst", "紫晶"),
    ("Invokist", "祈唤师"),
    ("Bomber", "投弹者"),
    ("Bracers", "护腕"),
    ("Nightmarauders", "梦魇掠夺者"),
    ("Terminites", "终末蚁"),
    ("Warpdruid", "扭曲德鲁伊"),
    ("Dreadmage", "恐惧法师"),
    ("Warprogue", "扭曲游荡者"),
    ("Obfusca", "朦胧"),
    ("River", "河"),
    ("Reaper", "收割者"),
    ("Desert", "沙漠"),
    ("Breaker", "破碎者"),
    ("Shattered", "破碎"),
    ("Corrupt", "腐化"),
    ("Voidwyrm", "虚空巨虫"),
    ("Judgement", "审判"),
    ("Pathseeker", "寻路者"),
    ("Sensei", "导师"),
    ("Mountain", "山"),
    ("Mycelial", "菌丝"),
    ("Mage", "法师"),
    ("Mushroom", "蘑菇"),
    ("Fang", "牙"),
    ("Forest", "森林"),
    ("Snowstrider", "踏雪者"),
    ("Turtler", "龟商"),
    ("Potions", "药剂"),
    ("Pies", "馅饼"),
    ("Sablespark", "黑火花"),
    ("Sisters", "姐妹"),
    ("Maker", "制造者"),
    ("Mechannihilator", "机歼灭者"),
    ("Engine", "引擎"),
    ("Mechaphoenix", "机凤凰"),
    ("Bombcrafter", "炸弹匠"),
    ("Feather", "羽"),
    ("Mender", "修复者"),
    ("Riftclaw", "裂隙爪"),
    ("Claws", "爪"),
    ("Hurricane", "飓风"),
    ("Warlock", "术士"),
    ("Correction", "校正"),
    ("Creation", "造物"),
    ("Seven", "七"),
    ("Hellstring", "狱弦"),
    ("Malevolence", "恶意"),
    ("Psychic", "心灵"),
    ("Amulet", "护符"),
    ("Ninja", "忍者"),
    ("Fae", "仙灵"),
    ("Chrome", "铬"),
    ("Hectic", "忙乱"),
    ("Scribe", "书记"),
    ("Henge", "环石"),
    ("Dandelion", "蒲公英"),
    ("Serpentcall", "唤蛇"),
    ("Combustion", "燃烧"),
    ("Battery", "电池"),
    ("Reclamax", "回收机"),
    ("Socket", "嵌口"),
    ("Ferromancer's", "铁术师的"),
    ("Helper", "助手"),
    ("Hole", "洞"),
    ("Deathseeker", "寻死者"),
    ("Elite", "精锐"),
    ("Scorn", "轻蔑"),
    ("Weeper", "哀泣者"),
    ("Fire", "火焰"),
    ("Ravenous", "贪婪"),
    ("Sordid", "污秽"),
    ("Asp", "蝮蛇"),
    ("Vaultbreaker", "破库"),
    ("Dreamer's", "梦者"),
    ("Glass", "玻璃"),
    ("Tower", "高塔"),
    ("Destiny", "命运"),
    ("Skeptic", "怀疑者"),
    ("Nook", "角落"),
    ("Prodigal", "浪子"),
    ("Treasures", "宝藏"),
    ("Study", "书房"),
    ("Starchild", "星之子"),
    ("Granger", "农夫"),
    ("Lionheart", "狮心"),
    ("Snake", "蛇"),
    ("Honey", "蜜"),
    ("Avatar", "化身"),
    ("Weapon", "武器"),
    ("Flinger", "投掷者"),
    ("Brazer", "铜匠"),
    ("Autobuilder", "自动建造机"),
    ("Wormhole", "虫洞"),
    ("Cog", "齿轮"),
    ("Synchronizer", "同步者"),
    ("Grease", "油污"),
    ("Abolisher", "废除者"),
    ("Nihilmancer", "虚无法师"),
    ("Canopic", "卡诺皮克"),
    ("Jar", "罐"),
    ("Shadowcaster", "影咏者"),
    ("Penumbral", "半影"),
    ("Soulslayer", "斩魂者"),
    ("Rise", "崛起"),
    ("Unchained", "挣脱"),
    ("Minotaur", "牛头人"),
    ("Whelp", "幼龙"),
    ("Fettered", "枷锁"),
    ("Vandal", "破坏"),
    ("Polaris", "北极星"),
    ("Nemesis", "宿敌"),
    ("Trickster", "诡术师"),
    ("Noxious", "毒害"),
    ("Moment", "片刻"),
    ("Clarity", "澄明"),
    ("Godslayer", "弑神者"),
    ("Moonlit", "月下"),
    ("Spider", "蜘蛛"),
    ("Wolf", "狼"),
    ("Acolyte", "侍僧"),
    ("Cosmic", "宇宙"),
    ("Protocol", "协议"),
    ("Pyromaniac", "纵火狂"),
    ("Astroblade", "星刃"),
    ("Astrolabe", "星盘"),
    ("Driller", "钻机"),
    ("Recyclicrab", "循环蟹"),
    ("Repurposer", "再造者"),
    ("Sprayer", "喷射器"),
    ("Annihilation", "歼灭"),
    ("Deathsworn", "誓死"),
    ("Soulshaper", "塑魂者"),
    ("Avenger", "复仇者"),
    ("Orb", "宝珠"),
    ("Acidic", "酸性"),
    ("Crawler", "爬行者"),
    ("Genie", "灯神"),
    ("Cackling", "狂笑"),
    ("Jackal", "豺狼"),
    ("Growmites", "增生螨"),
    ("Nothing", "虚无"),
    ("Man", "人"),
    ("Monastic", "寺院"),
    ("Tutor", "导师"),
    ("Judge", "审判者"),
    ("Reality", "现实"),
    ("Sculptor", "塑造者"),
    ("Righteous", "正义"),
    ("Temporal", "时光"),
    ("Truth", "真理"),
    ("Seeker", "追寻者"),
    ("Prince", "王子"),
    ("Loamspeaker", "沃土语者"),
    ("Demontrap", "捕魔阱"),
    ("Redeemer", "救赎者"),
    ("Starcaller", "唤星者"),
    ("Wildcall", "野性呼唤"),
    ("Cognition", "认知"),
    ("Foresight", "预见"),
    ("Monacle", "单片镜"),
    ("Magnet", "磁"),
    ("Omnicron", "全时者"),
    ("Portabillet", "便携弹"),
    ("Skyrocket", "冲天"),
    ("Zeta", "泽塔"),
    ("Arsenal", "武库"),
    ("Vanquisher", "征服者"),
    ("Darkwalker", "暗行者"),
    ("Demonborn", "魔生"),
    ("Spiritcaster", "魂咏者"),
    ("Tome", "典籍"),
    ("Voidfeeder", "饲虚者"),
    ("Deviant", "畸变"),
    ("Firestorm", "火暴"),
    ("Effigy", "偶像"),
    ("Herald", "先驱"),
    ("Lagoon", "潟湖"),
    ("Troll", "巨魔"),
    ("Mordant", "蚀骨"),
    ("Protean", "多变"),
    ("Slug", "蛞蝓"),
    ("Raging", "暴怒"),
    ("Ursine", "熊"),
    ("Serpent", "巨蛇"),
    ("Twisted", "扭曲"),
    ("Sphinx", "狮身人面"),
    ("Anointed", "涂油"),
    ("Shardfinder", "寻晶者"),
    ("Compass", "罗盘"),
    ("Valiant", "勇毅"),
    ("Gemcatcher", "捕晶者"),
    ("Otherworldly", "异界"),
    ("Devoted", "虔诚"),
    ("Ascendant", "飞升者"),
    ("Gladewyrm", "林间巨虫"),
    ("Gem", "晶石"),
    ("Leprechaun", "小矮妖"),
    ("Huntmaster", "猎主"),
    ("Mosaic", "镶嵌"),
    ("Horn", "号角"),
    ("Tribesman", "部族人"),
    ("Chieftain", "酋长"),
    ("Charging", "充能"),
    ("Crystalline", "水晶"),
    ("Dredger", "挖掘者"),
    ("Replication", "复制"),
    ("Scrabbler", "翻捡者"),
    ("Scrabbling", "翻捡"),
    ("Squad", "小队"),
    ("Yolothian", "约洛斯"),
    ("Monolith", "巨石"),
    ("Sentinel", "哨卫"),
    ("Champion", "冠军"),
    ("Cacklecast", "狂笑施法"),
    ("Wretch", "可怜虫"),
    ("Oxipede", "牛蜈"),
    ("Phasefiend", "相位邪魔"),
    ("Plunder", "掠夺"),
    ("Devil", "恶魔"),
    ("Smoke", "烟雾"),
    ("Lich", "巫妖"),
    ("Webclaw", "网爪"),
    ("Exiled", "流放者"),
    ("Outrider", "先驱骑手"),
    ("Neophyte", "新入门者"),
    ("Lucid", "清明"),
    ("Dreams", "诸梦"),
    ("Scryer", "占卜者"),
    ("Guru", "古鲁"),
    ("Forgotten", "遗忘"),
    ("Scripture", "经文"),
    ("True", "真正"),
    ("Animus", "魂魄"),
    ("Wreath", "花环"),
    ("Crown", "冠冕"),
    ("Air", "空中"),
    ("Support", "支援"),
    ("Squadron", "中队"),
    ("Defense", "防御"),
    ("Generator", "发生器"),
    ("Discovery", "发现"),
    ("Upgrade", "升级"),
    ("Gargoyle", "石像鬼"),
    ("Secluded", "隐秘"),
    ("Zero", "零"),
    ("Point", "点"),
    ("Exemplar", "典范"),
    ("Deathdealer", "死神"),
    ("Noble", "贵族"),
    ("Unmaker", "解构者"),
    ("Demonsbane", "恶魔克星"),
    ("Initiate's", "新兵的"),
    ("Gauntlets", "护手"),
    ("Clutch", "掌握"),
    ("Canon", "圣典"),
    ("Deathbound", "缚死"),
    ("Delver", "深掘者"),
    ("Timestream", "时流"),
    ("Voidforged", "虚空锻"),
    ("Foundation", "根基"),
    ("Giant", "巨人"),
    ("Betrayal", "背叛"),
    ("Discontent", "不满"),
    ("Terrorizing", "威吓"),
    ("Wailing", "哀嚎"),
    ("Spectre", "幽灵"),
    ("Nihilist", "虚无者"),
    ("Mercenary", "佣兵"),
    ("Tormented", "受折磨"),
    ("Benefactor", "恩主"),
    ("All", "万民"),
    ("Corruptor", "腐蚀者"),
    ("Foul", "污秽"),
    ("Replicant", "复制体"),
    ("Ironmind", "铁心"),
    ("Days", "往日"),
    ("Past", "过去"),
    ("Daybreak", "破晓"),
    ("Austere", "严苛"),
    ("Renewal", "更新"),
    ("Premonition", "预感"),
    ("Bell", "钟"),
    ("Leader", "首领"),
    ("Moonveil", "月纱"),
    ("Dawn", "黎明"),
    ("Starlight", "星光"),
    ("Sanctum", "圣所"),
    ("Overhaul", "大修"),
    ("Cleric", "神职者"),
    ("Prospector", "探矿者"),
    ("Builder", "建造者"),
    ("Bug", "虫"),
    ("Gnome", "侏儒"),
    ("Plasma", "等离子"),
    ("Conversion", "转化"),
    ("Port", "端口"),
    ("Sting", "毒刺"),
    ("Undaunted", "无畏"),
    ("Maniacal", "狂乱"),
    ("Riftgate", "裂隙门"),
    ("Conjuror", "咒术师"),
    ("Bargain", "交易"),
    ("Morbid", "病态"),
    ("Hammer", "锤"),
    ("Rootscryer", "根卜者"),
    ("Sanctuary", "圣所"),
    ("Surge", "浪涌"),
    ("Protector", "保护者"),
    ("Genesis", "创世"),
    ("Capsule", "舱"),
    ("Shepherd", "牧者"),
    ("Rebirth", "重生"),
    ("Turret", "炮塔"),
    ("Corrupted", "腐化"),
    ("Betrayed", "被弃"),
    ("Thorned", "棘刺"),
    ("Charger", "冲锋者"),
    ("Rejected", "废弃"),
    ("Exhaust", "废气"),
    ("Deathfinder", "寻死者"),
    ("Glutton", "贪食者"),
    ("Lord", "领主"),
    ("Deofol", "迪奥福尔"),
    ("Auspicious", "吉兆"),
    ("Nocturnal", "夜行"),
    ("Garden", "园丁"),
    ("Dragoon", "龙骑兵"),
    ("Ward", "守护"),
    ("Sleeping", "沉睡"),
    ("Dreamshaper", "塑梦者"),
    ("Alluring", "魅惑"),
    ("Hatchling", "幼体"),
    ("Fairy", "妖精"),
    ("Dreamtender", "守梦者"),
    ("Inventor", "发明家"),
    ("Planar", "位面"),
    ("Aperture", "孔径"),
    ("Detector", "探测器"),
    ("Synapse", "突触"),
    ("Deluxe", "豪华"),
    ("Capacitor", "电容"),
    ("Tank", "坦克"),
    ("Inquarry", "采石"),
    ("Hydra", "九头蛇"),
    ("Caustic", "腐蚀"),
    ("Dreamkiller", "弑梦者"),
    ("Loam", "沃土"),
    ("Summoner", "召唤师"),
    ("Fear", "恐惧"),
    ("Wielder", "持有者"),
    ("Fatality", "致命"),
    ("Harvester", "收割者"),
    ("Rust", "锈"),
    ("Thieving", "偷窃"),
    ("Gryphon", "狮鹫"),
    ("Tidestalker", "潮潜者"),
    ("Fen", "沼"),
    ("Trinket", "饰品"),
    ("Harpy", "鹰身女妖"),
    ("Deluding", "欺瞒"),
    ("Hulking", "庞大"),
    ("Crab", "蟹"),
    ("Puppetmaster", "傀儡师"),
    ("Fleeting", "飞逝"),
    ("Engulfing", "吞噬"),
    ("Kraken", "克拉肯"),
    ("Imaginative", "想象"),
    ("Reverie", "幻想"),
    ("Brainstorm", "头脑风暴"),
    ("Chronicle", "编年史"),
    ("Askaran", "阿斯卡拉"),
    ("Armor", "甲"),
    ("Lab", "实验室"),
    ("Censer", "香炉"),
    ("Armistice", "停战"),
    ("Wicked", "邪"),
    ("End", "终结"),
    ("Test", "试炼"),
    ("Faith", "信仰"),
    ("Aura", "灵光"),
    ("Respite", "喘息"),
    ("Blessing", "祝福"),
    ("Technological", "科技"),
    ("Leap", "跃进"),
    ("Order", "秩序"),
    ("Gear", "齿轮"),
    ("Stalk", "潜行"),
    ("Call", "呼唤"),
    ("Frenzy", "狂乱"),
    ("Scrap", "废料"),
    ("Shade", "暗影"),
    ("Dark", "黑暗"),
    ("Void", "虚空"),
    ("Dream", "梦"),
    ("Stone", "石"),
    ("Wild", "荒野"),
    ("Soul", "灵魂"),
    ("Star", "星"),
    ("Moon", "月"),
    ("Sun", "日"),
    ("Sea", "海"),
    ("Wind", "风"),
    ("Fire", "火"),
    ("Iron", "铁"),
    ("Gold", "金"),
    ("Green", "绿"),
    ("Black", "黑"),
    ("White", "白"),
    ("False", "虚假"),
    ("True", "真正"),
    ("Great", "大"),
    ("First", "初代"),
    ("Lost", "迷失"),
    ("Fallen", "堕落"),
    ("Chosen", "天选"),
    ("Eternal", "永恒"),
    ("Ancient", "上古"),
    ("Personal", "私人"),
    ("Nothing", "虚无"),
    ("All", "万民"),
    ("War", "战争"),
    ("Hope", "希望"),
    ("Fate", "命运"),
    ("Light", "光"),
    ("Darkness", "黑暗"),
    ("Shadow", "暗影"),
    ("Chaos", "混沌"),
    ("Order", "秩序"),
    ("Life", "生命"),
    ("Death", "死亡"),
    ("Time", "时光"),
    ("Dreams", "诸梦"),
    ("Stars", "群星"),
    ("Souls", "灵魂"),
    ("Heroes", "英雄"),
    ("Monsters", "怪物"),
    ("Constructs", "神器"),
]
