"""Shared English -> Simplified Chinese helpers for Ascension copy."""

from __future__ import annotations

import re

from name_lexicon import NAME_EXACT, NAME_PARTS, NAME_WORDS

# Longest-first. Keep ${ICON_*}, ${LABEL_*}, ${CLICK_*}, <sprite>, HTML tags intact.
EFFECT_PHRASES: list[tuple[str, str]] = [
    ("Once per turn, if there is no Monster under this, you may put a Monster from the center row under it.",
     "每回合一次，若此牌下没有怪物，你可以将中央牌列的一个怪物置于其下。"),
    ("After a certain amount of time, this transforms into something awesome!",
     "经过一段时间后，此牌会转化成某种很厉害的东西！"),
    ("Roll the Delirium Die.", "掷谵妄骰。"),
    ("Once per turn, when you acquire another Mechana Construct, you may put it directly into play.",
     "每回合一次，当你获取另一张机械神器时，你可以将其直接进入战场。"),
    ("You may spend it only to acquire a Mechana Construct.", "你只能用它来获取机械神器。"),
    ("You may spend it only to acquire Mechana Constructs.", "你只能用它来获取机械神器。"),
    ("the first time you defeat a Monster in the center row each turn", "每回合你首次击败中央牌列中的怪物时"),
    ("The first time you defeat a Monster in the center row each turn", "每回合你首次击败中央牌列中的怪物时"),
    ("the first time you play a Lifebound Hero each turn", "每回合你首次打出命约英雄时"),
    ("The first time you play a Lifebound Hero each turn", "每回合你首次打出命约英雄时"),
    ("This Monster can't be banished unless defeated.", "除非被击败，否则此怪物不可被放逐。"),
    ("Each opponent must choose a Construct they control and put the rest into their discard pile.",
     "每位对手须选择一张其控制的神器，将其余神器置入弃牌堆。"),
    ("Each opponent must put a Construct he controls into his discard pile.",
     "每位对手须将其控制的一张神器置入弃牌堆。"),
    ("in your hand or discard pile", "在你的手牌或弃牌堆"),
    ("in your discard pile", "在你的弃牌堆"),
    ("in their hand", "在其手牌中"),
    ("in your hand", "在你的手牌中"),
    ("in the center row", "在中央牌列"),
    ("from the center row", "从中央牌列"),
    ("from the center deck", "从中央牌库"),
    ("on top of your deck", "放到你的牌库顶"),
    ("on the bottom of your deck", "放到你的牌库底"),
    ("into your discard pile", "置入你的弃牌堆"),
    ("into his discard pile", "置入其弃牌堆"),
    ("into their discard pile", "置入其弃牌堆"),
    ("directly into play", "直接进入战场"),
    ("into play", "进入战场"),
    ("without paying its cost", "无需支付费用"),
    ("without paying their costs", "无需支付费用"),
    ("for free", "无需支付费用"),
    ("Take a card", "拿取一张卡牌"),
    ("Take a ", "拿取一个"),
    ("take a card", "拿取一张卡牌"),
    ("add that card", "将该卡牌加入"),
    ("add those cards", "将那些卡牌加入"),
    ("add them to", "将它们加入"),
    ("as though it were", "视为"),
    ("as though they were", "视为"),
    ("as though it was", "视为"),
    ("You do not have to", "你无需"),
    ("do not have to", "无需"),
    ("do not", "不"),
    ("Do not", "不要"),
    ("Each opponent must", "每位对手须"),
    ("each opponent must", "每位对手须"),
    ("Each player", "每位玩家"),
    ("each player", "每位玩家"),
    ("on the bottom of", "置于其底："),
    ("the bottom of", "底部"),
    ("this way", "以此方式"),
    ("Treat all", "将所有"),
    ("treat all", "将所有"),
    ("treat ", "视为"),
    ("Treat ", "视为"),
    ("among Constructs you control", "在你控制的神器之中"),
    ("Factions are", "派系为"),
    ("has more than", "拥有超过"),
    ("must destroy", "须摧毁"),
    ("all but one", "只留一个，其余"),
    ("either discards", "要么弃掉"),
    ("or puts", "要么放置"),
    ("the number of", "数量为"),
    ("discard Reclamax", "弃掉回收机"),
    ("from play", "从战场"),
    ("steal", "偷取"),
    ("Spend ", "花费"),
    ("spend ", "花费"),
    ("banish this", "放逐此牌"),
    ("take an extra turn", "进行一个额外回合"),
    ("after this one", "在此之后"),
    ("put it", "将它放置"),
    ("Put it", "将它放置"),
    ("Look at", "查看"),
    ("look at", "查看"),
    ("there is", "存在"),
    ("There is", "存在"),
    ("up to", "至多"),
    ("must ", "须"),
    ("Must ", "须"),
    ("more than", "超过"),
    ("less than", "低于"),
    ("the most", "最多的"),
    ("they have", "其拥有"),
    ("has ", "具有"),
    ("have ", "拥有"),
    ("both", "两者"),
    ("instead of", "而非"),
    ("the end of", "结束时"),
    ("return this", "将此牌返回"),
    ("replace them", "将它们替换"),
    ("replace it", "将它替换"),
    ("destroys", "摧毁"),
    ("destroy", "摧毁"),
    ("gained", "已获得"),
    ("value", "值"),
    ("recur", "再次发生"),
    ("Take ", "拿取"),
    ("take ", "拿取"),
    ("Add ", "加入"),
    ("add ", "加入"),
    ("as though it were", "视为"),
    ("as though they were", "视为"),
    ("without paying", "无需支付"),
    ("Once per turn, ", "每回合一次，"),
    ("once per turn, ", "每回合一次，"),
    ("Once per turn ", "每回合一次，"),
    ("Draw three cards", "抽三张牌"),
    ("Draw two cards", "抽两张牌"),
    ("Draw a card", "抽一张牌"),
    ("draw three cards", "抽三张牌"),
    ("draw two cards", "抽两张牌"),
    ("draw a card", "抽一张牌"),
    ("additional turn", "额外回合"),
    ("this turn", "本回合"),
    ("this Hero", "此英雄"),
    ("this Construct", "此神器"),
    ("this Monster", "此怪物"),
    ("Mechana Constructs", "机械神器"),
    ("Mechana Construct", "机械神器"),
    ("Lifebound Heroes", "命约英雄"),
    ("Lifebound Hero", "命约英雄"),
    ("Enlightened Heroes", "圣贤英雄"),
    ("Enlightened Hero", "圣贤英雄"),
    ("Void Heroes", "虚空英雄"),
    ("Void Hero", "虚空英雄"),
    ("center row", "中央牌列"),
    ("Center Row", "中央牌列"),
    ("discard pile", "弃牌堆"),
    ("Honor tokens", "荣誉点数"),
    ("honor tokens", "荣誉点数"),
    ("Honor Pool", "荣誉池"),
    ("Honor pool", "荣誉池"),
    ("Portal Deck", "传送门牌库"),
    ("Always available", "始终可用"),
    ("always available", "始终可用"),
    ("Unbanishable", "不可放逐"),
    ("unbanishable", "不可放逐"),
    ("You may ", "你可以"),
    ("you may ", "你可以"),
    ("If you do, ", "若你如此做，"),
    ("If you do ", "若你如此做，"),
    ("If you've played", "若你打出过"),
    ("If you have played", "若你打出过"),
    ("Reward: ", "奖励："),
    ("${LABEL_REWARD} ", "奖励："),
    ("Gain ", "获得"),
    ("gain ", "获得"),
    ("Defeat a Monster", "击败一个怪物"),
    ("Defeat a ", "击败一个"),
    ("defeat a Monster", "击败一个怪物"),
    ("Banish a card", "放逐一张卡牌"),
    ("Banish a ", "放逐一个"),
    ("banish a card", "放逐一张卡牌"),
    ("Acquire a Hero", "获取一个英雄"),
    ("Acquire a ", "获取一个"),
    ("acquire a Hero", "获取一个英雄"),
    ("Copy the effect of a Hero played this turn.", "复制本回合打出的一张英雄的效果。"),
    ("Copy the effect", "复制效果"),
    ("that has P", "战力值不高于"),
    ("that costs R", "费用不高于"),
    ("that costs ", "费用为"),
    ("or less", "或更低"),
    ("or more", "或更高"),
    ("each turn", "每回合"),
    ("each opponent", "每位对手"),
    ("Each opponent", "每位对手"),
    ("each player", "每位玩家"),
    ("Each player", "每位玩家"),
    ("your deck", "你的牌库"),
    ("your hand", "你的手牌"),
    ("the Void", "虚空区"),
    ("the void", "虚空区"),
    ("Action Area", "行动区"),
    ("End Turn", "结束回合"),
    ("When this enters the center row", "当此牌进入中央牌列时"),
    ("When this enters play", "当此牌进入战场时"),
    ("When this card enters play", "当此牌进入战场时"),
    ("the top card of the center deck", "传送门牌库顶的卡牌"),
    ("the top card of your deck", "你牌库顶的卡牌"),
    ("Reveal the top card of", "展示以下牌库顶的卡牌："),
    ("Reveal the top card", "展示牌库顶的卡牌"),
    ("Place it on top of your deck", "将它放到你的牌库顶"),
    ("put it directly into play", "将其直接进入战场"),
    ("Put it into play", "将它进入战场"),
    ("including this", "包括此牌"),
    ("While this is in play", "当此牌在战场时"),
    ("You may spend", "你可以花费"),
    ("you may spend", "你可以花费"),
    ("as though it was", "视为"),
    ("as though they were", "视为"),
    ("of equal or lower cost", "费用相等或更低"),
    ("of equal or less cost", "费用相等或更低"),
    ("or less cost", "或更低费用"),
    ("The next time you", "下次你"),
    ("the next time you", "下次你"),
    ("Any card underneath", "置于其下的任何卡牌"),
    ("cannot be acquired, banished, or defeated", "不能被获取、放逐或击败"),
    ("Choose one:", "选择一项："),
    ("Choose one -", "选择一项："),
    ("Choose a Hero", "选择一个英雄"),
    ("Choose a Construct", "选择一个神器"),
    ("Choose a Monster", "选择一个怪物"),
    ("Choose a card", "选择一张卡牌"),
    ("Choose an opponent", "选择一名对手"),
    ("Choose a player", "选择一名玩家"),
    ("copy its effect", "复制其效果"),
    ("copy their effects", "复制其效果"),
    ("under your control", "置于你的控制下"),
    ("you control", "你控制的"),
    ("they control", "其控制的"),
    ("he controls", "其控制的"),
    ("Destroy a Construct", "摧毁一个神器"),
    ("destroy a Construct", "摧毁一个神器"),
    ("destroy up to", "摧毁至多"),
    ("Draw it or defeat it", "抽起它或击败它"),
    ("place a Giant Rat", "放置一张巨鼠"),
    ("until Giant Rat is banished or defeated", "直到巨鼠被放逐或击败"),
    ("add it to their hand", "加入其手牌"),
    ("add it to your hand", "加入你的手牌"),
    ("face down underneath", "面朝下置于其下"),
    ("face up", "面朝上"),
    ("at random", "随机"),
    ("from their hand", "从其手牌"),
    ("from your hand", "从你的手牌"),
    ("from the Void", "从虚空区"),
    ("from the End of the Rainbow", "从彩虹尽头"),
    ("another player's control", "另一名玩家的控制"),
    ("once per faction", "每个派系仅一次"),
    ("This only happens once per faction", "每个派系仅触发一次"),
    ("double your power", "使你的战力翻倍"),
    ("Remove all Honor from the Honor pool", "将荣誉池中的荣誉全部移除"),
    ("Remove all Honor from the 荣誉池", "将荣誉池中的荣誉全部移除"),
    ("counts as a copy", "视为复制"),
    ("hasn’t been chosen", "尚未被选择"),
    ("hasn't been chosen", "尚未被选择"),
    ("No Faction:", "无派系："),
    ("Always Available", "始终可用"),
    ("Portal Deck", "传送门牌库"),
    ("Trophy Monsters", "战利品怪物"),
    ("Trophy Monster", "战利品怪物"),
    ("Soul counter", "灵魂指示物"),
    ("Soul counters", "灵魂指示物"),
    ("REWARD:", "奖励："),
    ("Reward:", "奖励："),
    ("FATE:", "天命："),
    ("Fate:", "天命："),
    ("ENERGIZE:", "充能："),
    ("Energize:", "充能："),
    ("EMPOWER:", "赋力："),
    ("Empower:", "赋力："),
    ("TROPHY:", "战利品："),
    ("PHANTASM:", "幻象："),
    ("TRANSFORM:", "转化："),
    ("Transform:", "转化："),
    ("MULTI-UNITE:", "多重联合："),
    ("UNITE:", "联合："),
    ("Ongoing Trophy:", "持续战利品："),
    ("Event Trophy:", "事件战利品："),
    ("Soul Gem", "灵魂宝石"),
    ("Wish counter", "愿望指示物"),
    ("Wish counters", "愿望指示物"),
    ("Delirium Die", "谵妄骰"),
    ("roll the Delirium Die", "掷谵妄骰"),
    ("Roll the Delirium Die", "掷谵妄骰"),
    ("your Dreamscape", "你的梦境"),
    ("their Dreamscape", "其梦境"),
    ("the Dreamscape", "梦境"),
    ("Dreamscape", "梦境"),
    ("Gain control of", "获得对以下的控制："),
    ("gain control of", "获得对以下的控制："),
    ("look at the top", "查看牌库顶"),
    ("Look at the top", "查看牌库顶"),
    ("add a card to", "将一张卡牌加入"),
    ("Add a card to", "将一张卡牌加入"),
    ("add them to", "将它们加入"),
    ("Instead,", "改为，"),
    ("instead,", "改为，"),
    ("instead", "改为"),
    ("Ignore the rest of this", "忽略此牌的其余"),
    ("Transform this into", "将此牌转化为"),
    ("transform this into", "将此牌转化为"),
    ("Once per turn", "每回合一次"),
    ("once per turn", "每回合一次"),
    ("an extra", "额外的"),
    ("an additional", "额外的"),
    ("the acquired card", "所获取的卡牌"),
    ("acquired card", "所获取的卡牌"),
    ("current Event", "当前事件"),
    ("Event Trophy", "事件战利品"),
    ("Treasure", "宝藏"),
    ("Auction", "竞拍"),
    ("Insight", "洞察"),
    ("Energize", "充能"),
    ("Unite", "联合"),
    ("Rally", "集结"),
    ("this card's", "此牌的"),
    ("this card", "此牌"),
    ("this Monster", "此怪物"),
    ("this Construct", "此神器"),
    ("this Hero", "此英雄"),
    ("If it is Day", "若当前为昼"),
    ("If it is Night", "若当前为夜"),
    ("non-trophy Monster", "非战利品怪物"),
    ("non-Trophy Monster", "非战利品怪物"),
    ("Transformed", "已转化"),
    ("underneath", "其下"),
    ("Whenever", "每当"),
    ("controls", "控制"),
    ("draws", "抽"),
    ("Repeat this", "重复此"),
    ("Repeat", "重复"),
    ("Dreamborn", "梦生"),
    ("shuffle", "洗牌"),
    ("in addition to", "此外还"),
    ("in addition", "此外"),
    ("directly", "直接"),
    ("expansion", "扩展"),
    ("Portals", "传送门"),
    ("Portal", "传送门"),
    ("multiple", "多名"),
    ("tied", "平手"),
    ("seven", "七张"),
    ("Starting with you", "从你开始"),
    ("Starting", "从"),
    ("owners", "拥有者"),
    ("same name", "同名"),
    ("rounded", "进位"),
    ("abilities", "异能"),
    ("ability", "异能"),
    ("defeating", "击败"),
    ("Construct", "神器"),
    ("Contruct", "神器"),
    ("Consruct", "神器"),
    ("contol", "控制"),
    ("minimum", "最少"),
    ("reveals", "展示"),
]

EFFECT_WORDS: list[tuple[str, str]] = [
    ("Heavy Infantry", "重装步兵"),
    ("Mechana Constructs", "机械神器"),
    ("Mechana Construct", "机械神器"),
    ("Mechana Heroes", "机械英雄"),
    ("Mechana Hero", "机械英雄"),
    ("Lifebound Heroes", "命约英雄"),
    ("Lifebound Hero", "命约英雄"),
    ("Enlightened Heroes", "圣贤英雄"),
    ("Enlightened Hero", "圣贤英雄"),
    ("Void Heroes", "虚空英雄"),
    ("Void Hero", "虚空英雄"),
    ("center deck", "传送门牌库"),
    ("Center Deck", "传送门牌库"),
    ("center row", "中央牌列"),
    ("Center Row", "中央牌列"),
    ("discard pile", "弃牌堆"),
    ("honor tokens", "荣誉点数"),
    ("Honor tokens", "荣誉点数"),
    ("Honor token", "荣誉点数"),
    ("honor token", "荣誉点数"),
    ("Constructs", "神器"),
    ("constructs", "神器"),
    ("Construct", "神器"),
    ("construct", "神器"),
    ("Monsters", "怪物"),
    ("Monster", "怪物"),
    ("Heroes", "英雄"),
    ("Hero", "英雄"),
    ("Mystic", "秘教士"),
    ("Militia", "民兵"),
    ("Apprentice", "学徒"),
    ("Cultist", "邪教徒"),
    ("Mechana", "机械"),
    ("Lifebound", "命约"),
    ("Enlightened", "圣贤"),
    ("faction", "派系"),
    ("factions", "派系"),
    ("Acquire", "获取"),
    ("acquire", "获取"),
    ("Defeat", "击败"),
    ("defeat", "击败"),
    ("defeated", "被击败"),
    ("Banish", "放逐"),
    ("banish", "放逐"),
    ("banished", "被放逐"),
    ("Discard", "弃掉"),
    ("discard", "弃掉"),
    ("Destroy", "摧毁"),
    ("destroy", "摧毁"),
    ("Reveal", "展示"),
    ("reveal", "展示"),
    ("Draw", "抽"),
    ("draw", "抽"),
    ("Place", "放置"),
    ("place", "放置"),
    ("Choose", "选择"),
    ("choose", "选择"),
    ("control", "控制"),
    ("enters", "进入"),
    ("played", "打出过"),
    ("play", "打出"),
    ("Play", "打出"),
    ("including", "包括"),
    ("additional", "额外的"),
    ("another", "另一"),
    ("their", "其"),
    ("Then", "然后"),
    ("then", "然后"),
    ("When", "当"),
    ("when", "当"),
    ("While", "当"),
    ("while", "当"),
    ("Once", "一次"),
    ("once", "一次"),
    ("next", "下一"),
    ("cost", "费用"),
    ("costs", "费用为"),
    ("spend", "花费"),
    ("Spend", "花费"),
    ("pay", "支付"),
    ("Pay", "支付"),
    ("put", "放置"),
    ("Put", "放置"),
    ("cards", "卡牌"),
    ("card", "卡牌"),
    ("deck", "牌库"),
    ("hand", "手牌"),
    ("player", "玩家"),
    ("players", "玩家"),
    ("opponent", "对手"),
    ("opponents", "对手"),
    ("Honor", "荣誉"),
    ("honor", "荣誉"),
    ("Power", "战力"),
    ("power", "战力"),
    ("Runes", "符文"),
    ("Rune", "符文"),
    ("runes", "符文"),
    ("rune", "符文"),
    ("Void", "虚空区"),
    ("void", "虚空区"),
    ("less", "更低"),
    ("equal", "相等"),
    ("random", "随机"),
    ("return", "返回"),
    ("under", "其下"),
    ("other", "其他"),
    ("counts", "视为"),
    ("have", "拥有"),
    ("each", "每个"),
    ("all", "所有"),
    ("any", "任意"),
    ("one", "一"),
    ("two", "两"),
    ("three", "三"),
    ("may", "可以"),
    ("Insight", "洞察"),
    ("insight", "洞察"),
    ("Energy", "能量"),
    ("energy", "能量"),
    ("Event", "事件"),
    ("event", "事件"),
    ("Treasure", "宝藏"),
    ("treasure", "宝藏"),
    ("Dreamscape", "梦境"),
    ("Unite", "联合"),
    ("unite", "联合"),
    ("Rally", "集结"),
    ("rally", "集结"),
    ("Transform", "转化"),
    ("transform", "转化"),
    ("Empower", "赋力"),
    ("empower", "赋力"),
    ("Ongoing", "持续"),
    ("ongoing", "持续"),
    ("Trophy", "战利品"),
    ("trophy", "战利品"),
    ("Fate", "天命"),
    ("Auction", "竞拍"),
    ("auction", "竞拍"),
    ("effect", "效果"),
    ("effects", "效果"),
    ("Effect", "效果"),
    ("instead", "改为"),
    ("Instead", "改为"),
    ("your", "你的"),
    ("Your", "你的"),
    ("you", "你"),
    ("You", "你"),
    ("this", "此"),
    ("This", "此"),
    ("If", "若"),
    ("if", "若"),
    ("and", "和"),
    ("And", "和"),
    ("or", "或"),
    ("Or", "或"),
    ("from", "从"),
    ("From", "从"),
    ("with", "以"),
    ("With", "以"),
    ("into", "置入"),
    ("Into", "置入"),
    ("that", "该"),
    ("That", "该"),
    ("them", "它们"),
    ("those", "那些"),
    ("than", "于"),
    ("for", "以"),
    ("For", "以"),
    ("are", "为"),
    ("is", "为"),
    ("as", "作为"),
    ("As", "作为"),
    ("in", "在"),
    ("In", "在"),
    ("on", "在"),
    ("On", "在"),
    ("it", "它"),
    ("It", "它"),
    ("its", "其"),
    ("Its", "其"),
    ("of", "的"),
    ("Of", "的"),
    ("to", "以"),
    ("To", "以"),
    ("the", ""),
    ("The", ""),
    ("an", ""),
    ("An", ""),
    ("a", ""),
    ("A", ""),
    ("Take", "拿取"),
    ("take", "拿取"),
    ("Add", "加入"),
    ("add", "加入"),
    ("free", "无需支付费用"),
    ("treat", "视为"),
    ("Treat", "视为"),
    ("must", "须"),
    ("Must", "须"),
    ("among", "之中"),
    ("after", "之后"),
    ("though", "如同"),
    ("were", "处于"),
    ("steal", "偷取"),
    ("either", "要么"),
    ("discards", "弃掉"),
    ("puts", "放置"),
    ("Each", "每位"),
    ("number", "数量"),
    ("bottom", "底部"),
    ("way", "方式"),
    ("there", "那里"),
    ("They", "他们"),
    ("they", "他们"),
    ("but", "但"),
    ("not", "不"),
    ("Not", "不"),
    ("no", "没有"),
    ("No", "没有"),
    ("be", "是"),
    ("he", "他"),
    ("He", "他"),
    ("she", "她"),
    ("She", "她"),
    ("his", "他的"),
    ("His", "他的"),
    ("her", "她的"),
    ("Her", "她的"),
    ("we", "我们"),
    ("We", "我们"),
    ("us", "我们"),
    ("me", "我"),
    ("my", "我的"),
    ("who", "谁"),
    ("what", "什么"),
    ("will", "将"),
    ("can", "能"),
    ("was", "曾是"),
    ("would", "会"),
    ("could", "能够"),
    ("should", "应当"),
    ("just", "只是"),
    ("even", "甚至"),
    ("only", "只"),
    ("always", "总是"),
    ("never", "从不"),
    ("still", "仍然"),
    ("also", "也"),
    ("new", "新"),
    ("see", "看见"),
    ("know", "知道"),
    ("find", "找到"),
    ("come", "来"),
    ("by", "被"),
    ("at", "在"),
    ("up", "至多"),
    ("out", "出"),
    ("over", "超过"),
    ("more", "更多"),
    ("most", "最多"),
    ("both", "两者"),
    ("end", "结束"),
    ("time", "次"),
    ("world", "世界"),
    ("life", "生命"),
    ("death", "死亡"),
    ("light", "光"),
    ("do", "做"),
    ("did", "做了"),
    ("has", "具有"),
    ("had", "曾有"),
    ("been", "已经"),
    ("these", "这些"),
    ("which", "其"),
    ("where", "哪里"),
    ("Factions", "派系"),
    ("monster", "怪物"),
    ("after", "之后"),
    ("gained", "已获得"),
    ("value", "值"),
    ("replace", "替换"),
    ("destroys", "摧毁"),
    ("recur", "再次发生"),
    ("highest", "最高"),
    ("lowest", "最低"),
    ("adjacent", "相邻"),
    ("during", "在期间"),
    ("named", "被命名为"),
    ("Name", "命名"),
    ("considered", "视为"),
    ("worth", "价值为"),
    ("current", "当前"),
    ("Current", "当前"),
    ("first", "首先"),
    ("leaves", "离开"),
    ("game", "游戏"),
    ("ends", "结束"),
    ("odd", "奇数"),
    ("even cost", "偶数费用"),
    ("odd cost", "奇数费用"),
    ("much", "等量的"),
    ("Cultists", "邪教徒"),
    ("Fanatics", "狂信者"),
    ("rewards", "奖励"),
    ("top", "顶部"),
    ("aquire", "获取"),
    ("prevent", "防止"),
    ("being", "被"),
    ("defeats", "击败"),
    ("gains", "获得"),
    ("until", "直到"),
    ("paying", "支付"),
    ("second", "第二"),
    ("destroyed", "被摧毁"),
    ("destroying", "摧毁"),
    ("Contructs", "神器"),
    ("copy", "复制"),
    ("Copy", "复制"),
    ("temple", "神殿"),
    ("Temple", "神殿"),
    ("tribe", "部落"),
    ("Phantasm", "幻象"),
    ("phantasm", "幻象"),
    ("plunder", "掠夺"),
    ("Plunder", "掠夺"),
    ("four", "四"),
    ("five", "五"),
    ("six", "六"),
    ("Day", "昼"),
    ("Night", "夜"),
    ("gremlin", "小妖"),
    ("listed", "列出的"),
    ("Scion", "后裔"),
    ("order", "秩序"),
    ("acquires", "获取"),
    ("chosen", "所选"),
    ("tie", "平局"),
    ("case", "情况"),
    ("All", "所有"),
    ("Cards", "卡牌"),
    ("Card", "卡牌"),
    ("go", "进入"),
    ("turn", "回合"),
    ("Turn", "回合"),
    ("him", "他"),
    ("without", "没有"),
    ("everything", "一切"),
    ("need", "需要"),
    ("blood", "血"),
    ("path", "道路"),
    ("night", "夜晚"),
    ("knowledge", "知识"),
    ("many", "许多"),
    ("great", "伟大"),
    ("every", "每个"),
    ("through", "穿过"),
    ("follow", "跟随"),
    ("nothing", "虚无"),
    ("impossible", "不可能"),
    ("our", "我们的"),
    ("now", "现在"),
    ("said", "说"),
    ("seek", "寻求"),
    ("mind", "心智"),
    ("so", "如此"),
    ("future", "未来"),
    ("let", "让"),
    ("found", "发现"),
    ("shards", "碎片"),
    ("It's", "它是"),
    ("it's", "它是"),
    ("I'm", "我是"),
    ("don't", "不"),
    ("doesn't", "不"),
    ("can't", "不能"),
    ("won't", "不会"),
    ("PHANTASM", "幻象"),
    ("Phantasm", "幻象"),
    ("AND", "和"),
    ("Recur", "再次发生"),
    ("RECUR", "再次发生"),
    ("PLUNDER", "掠夺"),
    ("Pasythea", "帕西提亚"),
    ("Emri", "艾姆瑞"),
    ("Gremlin", "小妖"),
    ("repeat", "重复"),
    ("Reward", "奖励"),
    ("double", "双倍"),
    ("revealed", "已展示"),
    ("anywhere", "任意处"),
    ("above", "上方"),
    ("below", "下方"),
    ("replaced", "被替换"),
    ("transformed", "已转化"),
    ("remove", "移除"),
    ("seventh", "第七"),
    ("discarded", "已弃掉"),
    ("pool", "池"),
    ("cannot", "不能"),
    ("copied", "被复制"),
    ("enter", "进入"),
    ("twice", "两次"),
    ("acquired", "已获取"),
    ("Dream", "梦"),
]

NAME_PHRASES: list[tuple[str, str]] = [
    ("Apprentice", "学徒"),
    ("Militia", "民兵"),
    ("Mystic", "秘教士"),
    ("Heavy Infantry", "重装步兵"),
    ("Cultist", "邪教徒"),
    ("Fanatic", "狂信者"),
    ("Arha Initiate", "亚哈新兵"),
    ("Arha Templar", "亚哈圣殿武士"),
    ("Arha Sensei", "亚哈导师"),
    ("Arha Guardian", "亚哈守卫"),
    ("Arha Sanctuary", "亚哈圣所"),
    ("Lifebound Initiate", "生命新兵"),
    ("Mechana Initiate", "机械新兵"),
    ("Void Initiate", "虚空新兵"),
    ("Watchmaker's Altar", "制表师祭坛"),
    ("Hedron Link Device", "多面体连接装置"),
    ("Hedron Cannon", "多面体加农"),
    ("Hedron Flare", "多面体闪耀"),
    ("Rocket Courier X-99", "火箭信使X-99"),
    ("Yggdrasil Staff", "世界树法杖"),
    ("Avatar of the Fallen", "堕落者化身"),
    ("Earth Tyrant", "大地暴君"),
    ("Sea Tyrant", "海中暴君"),
    ("Wind Tyrant", "风之暴君"),
    ("Samael the Fallen", "堕落之神萨麦尔"),
    ("Samael's Trickster", "萨麦尔的诡术师"),
    ("Wolf Shaman", "狼萨满"),
    ("Flytrap Witch", "捕蝇草女巫"),
    ("Temple Librarian", "神殿图书管理员"),
    ("Master Dhartha", "达萨大师"),
    ("Oziah the Peerless", "无双的奥齐亚"),
    ("Ascetic of the Lidless Eye", "无目之眼苦行僧"),
    ("Seer of the Forked Path", "歧路预言者"),
    ("Twofold Askara", "双重阿斯卡拉"),
    ("Runic Lycanthrope", "符文狼化人"),
    ("Druids of the Stone Circle", "石环德鲁伊"),
    ("Cetra, Weaver of Stars", "织星者塞特拉"),
    ("Emri, One with the Void", "与虚空合一的艾姆瑞"),
    ("The All-Seeing Eye", "全视之眼"),
    ("Tablet of Time's Dawn", "时晓石板"),
    ("Voidthirster", "渴虚者"),
    ("Shade of the Black Watch", "黑卫之影"),
    ("Corrosive Widow", "腐蚀寡妇"),
    ("Mistake of Creation", "造物之误"),
    ("Tormented Soul", "受折磨的灵魂"),
    ("Demon Slayer", "恶魔杀手"),
    ("Shadow Star", "暗影之星"),
    ("Spike Vixen", "尖刺雌狐"),
    ("Avatar Golem", "化身魔像"),
    ("Burrower Mark II", "钻地机II型"),
    ("Reactor Monk", "反应堆僧侣"),
    ("The Grand Design", "宏伟设计"),
    ("Arbiter of the Precipice", "悬崖仲裁者"),
    ("Snapdragon", "金鱼草"),
    ("Landtalker", "大地说书人"),
    ("Mephit", "恶臭精"),
    ("Muramasa", "村正"),
    ("Giant Rat", "巨鼠"),
    ("Rat King", "鼠王"),
    ("Pathwarden", "巡路者"),
    ("Deep Drone", "深潜无人机"),
    ("Void Mesmer", "虚空催眠师"),
    ("Journeyman Sage", "旅者贤者"),
    ("Askara of Fortune", "幸运阿斯卡拉"),
    ("Ring of Life", "生命之环"),
    ("Ender of Days", "终日者"),
    ("Leprechaun", "小矮妖"),
    ("Pot of Gold", "金罐"),
    ("Soul Collector", "集魂者"),
    ("Moon Staff", "月杖"),
    ("Control Room", "控制室"),
    ("Lotus Siren", "莲花海妖"),
    ("Aether Channeler", "以太引导者"),
    ("Spirit of the Ancients", "上古之灵"),
    ("Temporal Excavator", "时光发掘者"),
    ("Eternal Tormentor", "永恒折磨者"),
    ("Explosive Swarm", "爆裂虫群"),
    ("Constricting Horror", "绞杀恐魔"),
    ("Big Bad Bunny", "大坏兔子"),
    ("Nethersnare", "冥界陷阱"),
    ("Kythis, the Gatekeeper", "守门人凯西斯"),
    ("Vedah, Sage of Swords", "剑贤维达"),
    ("Miles, Golden Prodigy", "黄金神童迈尔斯"),
    ("Cetra, Guide of Ogo", "奥戈向导塞特拉"),
]

NAME_SUFFIXES: list[tuple[str, str]] = [
    ("Initiate", "新兵"),
    ("Templar", "圣殿武士"),
    ("Disciple of ", "之徒·"),
    ("Scion of ", "后裔·"),
    ("Avatar of ", "化身·"),
    ("Trial", "试炼"),
    ("Familiar", "使魔"),
    ("Tyrant", "暴君"),
    ("Shaman", "萨满"),
    ("Witch", "女巫"),
    ("Monk", "僧侣"),
    ("Priest", "祭司"),
    ("Magus", "魔导师"),
    ("Golem", "魔像"),
    ("Cannon", "加农"),
    ("Courier", "信使"),
    ("Altar", "祭坛"),
    ("Staff", "法杖"),
    ("Blade", "刃"),
    ("Shield", "盾"),
    ("Helm", "盔"),
    ("Star", "之星"),
    ("Soul", "之魂"),
    ("Horror", "恐魔"),
    ("Swarm", "虫群"),
    ("Drone", "无人机"),
    ("Warden", "守卫"),
    ("Keeper", "看守"),
    ("Weaver", "编织者"),
    ("Slayer", "斩杀者"),
    ("Bane", "克星"),
    ("Born of Battle", "战生"),
    ("Lightbringer", "携光者"),
    ("Soulstealer", "窃魂者"),
    ("Shadowslayer", "斩影者"),
    ("Demonsbane", "恶魔克星"),
    ("the Unmaker", "解构者"),
    ("Soulslayer", "斩魂者"),
    ("Judge of Logos", "逻各斯审判者"),
    ("Matron of Stars", "星辰主母"),
    ("Benefactor of All", "万民之恩"),
    ("Celestial Body", "天体"),
    ("Voidmother", "虚空之母"),
    ("One with the Void", "与虚空合一"),
    ("the Fallen", "堕落者"),
    ("the Peerless", "无双者"),
    ("the Gatekeeper", "守门人"),
    ("the Honored", "受誉者"),
]


def protect_tokens(text: str) -> tuple[str, list[str]]:
    tokens: list[str] = []

    def stash(m: re.Match) -> str:
        tokens.append(m.group(0))
        return f"\x00T{len(tokens) - 1}\x00"

    out = re.sub(r"\$\{[^}]+\}", stash, text)
    out = re.sub(r"<sprite=[^>]+>", stash, out)
    out = re.sub(r"</?[A-Za-z][^>]*>", stash, out)
    return out, tokens


def restore_tokens(text: str, tokens: list[str]) -> str:
    def unstash(m: re.Match) -> str:
        return tokens[int(m.group(1))]

    return re.sub(r"\x00T(\d+)\x00", unstash, text)


def strip_drop_cap(text: str) -> str:
    text = text.replace("\ufffd", "Ae").replace("Æ", "Ae").replace("æ", "ae")
    text = re.sub(
        r"<size=\s*[^>]*>\s*(.*?)\s*</size>(?:<space=[^>]*>)?",
        r"\1",
        text,
        flags=re.I,
    )
    text = text.replace("HSedron", "Hedron")
    return text


def _compile_ascii_pairs(pairs: list[tuple[str, str]]) -> list[tuple[re.Pattern[str], str]]:
    seen: set[str] = set()
    compiled: list[tuple[re.Pattern[str], str]] = []
    for en, zh in sorted(pairs, key=lambda x: len(x[0]), reverse=True):
        if not en or en in seen:
            continue
        seen.add(en)
        compiled.append((re.compile(rf"(?<![A-Za-z']){re.escape(en)}(?![A-Za-z'])"), zh))
        if en.isalpha():
            compiled.append((re.compile(rf"(?<![A-Za-z']){re.escape(en)}'s(?![A-Za-z'])"), zh + "之"))
    return compiled


_EFFECT_WORD_RES = _compile_ascii_pairs(EFFECT_WORDS)
_NAME_WORD_RES = _compile_ascii_pairs(NAME_WORDS)
_NAME_EXACT_RES = _compile_ascii_pairs(
    [(en, zh) for en, zh in NAME_EXACT.items() if en and zh and en != zh and len(en) >= 3]
)
_NAME_PARTS_SORTED = sorted(NAME_PARTS, key=lambda x: len(x[0]), reverse=True)
_EFFECT_PHRASES_SORTED = sorted(EFFECT_PHRASES, key=lambda x: len(x[0]), reverse=True)
_SPACE_RE = re.compile(r"[ ]{2,}")
_PUNCT_SPACE_RE = re.compile(r" +([，。；：？！])")


def apply_phrases(text: str, phrases: list[tuple[str, str]]) -> str:
    out = text
    for en, zh in phrases:
        if en:
            out = out.replace(en, zh)
    return out


def ascii_sub(text: str, en: str, zh: str) -> str:
    """Replace `en` when not inside another ASCII word. CJK is a valid boundary."""
    return re.sub(rf"(?<![A-Za-z']){re.escape(en)}(?![A-Za-z'])", zh, text)


def apply_words(text: str) -> str:
    out = text
    for pat, zh in _EFFECT_WORD_RES:
        out = pat.sub(zh, out)
    out = _SPACE_RE.sub(" ", out)
    out = _PUNCT_SPACE_RE.sub(r"\1", out)
    return out.strip()


def polish_copy(text: str) -> str:
    """Collapse leftover English function words and tidy punctuation."""
    out = text.replace("'s", "之")
    out = _SPACE_RE.sub(" ", out)
    out = re.sub(r" +([，。；：？！,.])", r"\1", out)
    out = re.sub(r"([，。；：])\.", r"\1", out)
    out = out.replace("..", "。").replace(" .", "。").replace(" ,", "，")
    out = re.sub(r"([\u4e00-\u9fff]) ([A-Za-z])", r"\1\2", out)
    out = re.sub(r"([A-Za-z]) ([\u4e00-\u9fff])", r"\1\2", out)
    out = re.sub(r"([\u4e00-\u9fff]) ([\u4e00-\u9fff])", r"\1\2", out)
    out = _SPACE_RE.sub(" ", out)
    return out.strip()


def apply_card_names(text: str) -> str:
    out = text
    for pat, zh in _NAME_EXACT_RES:
        out = pat.sub(zh, out)
    return out


def translate_effect(text: str) -> str:
    if not text:
        return ""
    raw, tokens = protect_tokens(text)
    raw = apply_phrases(raw, _EFFECT_PHRASES_SORTED)
    raw = apply_card_names(raw)
    raw = _apply_name_parts(raw)
    raw = re.sub(r"(\d+)R\b", r"\1符文", raw)
    raw = re.sub(r"(\d+)P\b", r"\1战力", raw)
    raw = re.sub(r"(\d+)H\b", r"\1荣誉", raw)
    raw = re.sub(r"(\d+)I\b", r"\1洞察", raw)
    raw = apply_words(raw)
    raw = polish_copy(raw)
    return restore_tokens(raw, tokens)


def _apply_name_parts(text: str) -> str:
    out = text
    for en, zh in _NAME_PARTS_SORTED:
        out = out.replace(en, zh)
    for pat, zh in _NAME_WORD_RES:
        out = pat.sub(zh, out)
    return out


def translate_name(text: str) -> str:
    if not text:
        return ""
    base = strip_drop_cap(text).strip()
    base = re.sub(r"\s+", " ", base)
    key = re.sub(r"\s+(10TH|SoS|RoV|RU|v2)$", "", base, flags=re.I).strip()
    if key in NAME_EXACT:
        suffix = base[len(key) :].strip()
        return NAME_EXACT[key] if not suffix else NAME_EXACT[key]
    if base in NAME_EXACT:
        return NAME_EXACT[base]
    for en, zh in sorted(NAME_PHRASES, key=lambda x: len(x[0]), reverse=True):
        if base == en or key == en:
            return zh
        if en in base and len(en) > 8:
            base = base.replace(en, zh)
    out = _apply_name_parts(base)
    for en, zh in sorted(NAME_SUFFIXES, key=lambda x: len(x[0]), reverse=True):
        out = out.replace(en, zh)
    out = re.sub(r"\b(of|Of|the|The)\b", "", out)
    out = re.sub(r"'s\b", "之", out)
    out = out.replace(",", "·").replace(":", "：").replace(" - ", "：")
    out = re.sub(r"\s+", "", out)
    out = out.replace("··", "·").strip("·")
    return out


FLAVOR_EXACT: dict[str, str] = {
    "Penalty for InfRingEment:<br>1.  termination<br>2.  onversion to organic scrap.": "违规处罚：<br>1. 终止运行<br>2. 转化为有机废料。",
    "Those who are still sane after the initiation rites are allowed to become watchers or arbiters.": "通过入会仪式后仍保持神智清醒者，才获准成为守望者或仲裁者。",
    "Each evening, the newcomer would climb the parapet and howl mournfully at the moon. On the third night, the moon howled back.": "每个傍晚，新来者都会爬上城垛，对着月亮哀嚎。到了第三夜，月亮回应了他。",
    "She was guide to both would-be leaders, but only the Godslayer reached the other side of the swamp. His rival simply vanished.": "她曾为两位争当领袖者领路，但只有弑神者走到了沼泽的另一边。他的对手就此消失。",
    "Enhancements over x-50 model: <br>1.  Increased speed<br>2 . (BeTa)  - Steering ": "相对 x-50 型号的改进：<br>1. 速度提升<br>2.（测试）转向",
    "For countless centuries in Ogo the order of the Stone Circle worked to deepen their connection to all living things.": "无数世纪以来，奥戈的石环教团致力于加深他们与万物的联系。",
    "There is no deadlier poison than pride.": "没有比骄傲更致命的毒药。",
    "Sharpen the mind, and the sword will follow.": "磨砺心智，剑自随之。",
    "You've got mail!": "你有新邮件！",
    "Nope, nope, nope.": "不行，不行，不行。",
    "None faster, none deadlier.": "无人更快，无人更致命。",
    "Sometimes, the curious become the mad.": "有时，好奇会变成疯狂。",
    "Level 6 - clarity.<br>level 7 - epiphany.<br>level 8 - martyrdom": "第六层——澄明。<br>第七层——顿悟。<br>第八层——殉道。",
    "initiate transformation.": "启动转化。",
    "An unheeded raven begets a thousand crows.": "被忽视的渡鸦，会招来千只乌鸦。",
    "hedron core temperature mustbe maintained": "必须维持多面体核心温度",
    "\"Show off...\"": "「爱现……」",
    "TOTAL crew - 23<br>10 wheelmen, 12 operators,1 certified barrel technician ": "编制 23 人<br>10 名驾驶员，12 名操作员，1 名持证炮管技师",
    "Loss acceptable. Continue operations.": "损失可接受。继续作业。",
    "Repairs complete. Unit operational.": "维修完毕。机组可投入运作。",
    "Collateral damage: acceptable.": "附带损害：可接受。",
    "Mmmmmrrrggllhhl!": "嗯嗯嗯咕噜咕噜！",
    "Shards detected. excavation underway.": "侦测到碎片。挖掘进行中。",
    "They're magically delicious.": "它们有种魔法般的美味。",
    "Shards compatible. Adaptation underway.": "碎片兼容。适应进行中。",
    "Double word score": "双倍单词得分",
    "Always count the shadows.": "永远要数清影子。",
    "positively electrifying": "确实令人电击。",
    "\"Because exhaust vent maintenance wasn't already dangerous enough.\"": "「就因为排风口维护还不够危险。」",
    "Yay, visitors!": "太好了，有客人！",
    "Nope.": "不行。",
    "Absolute corruption powers absolutely.": "绝对的腐化带来绝对的力量。",
    "Big Badaboom.": "大爆炸。",
    "Dirty deeds, done dirt cheap.": "脏活累活，价格便宜。",
    "Knock, knock!": "敲敲！",
    "Safe travels!": "一路平安！",
    "Recycle. Rebuild. Reuse.": "回收。重建。再利用。",
    "OBJECT RETRieveD.  UNKNOWNLIFE FORMs Detected. REquestinstructions.": "物体已回收。侦测到未知生命体。请求指示。",
    "Get Over Here!": "过来！",
    "They're everywhere!": "它们无处不在！",
}


def translate_flavor(text: str) -> str:
    if not text:
        return ""
    plain = strip_drop_cap(text).strip().strip('"')
    if plain in FLAVOR_EXACT:
        return FLAVOR_EXACT[plain]
    collapsed = re.sub(r"\s+", " ", plain)
    for en, zh in FLAVOR_EXACT.items():
        if re.sub(r"\s+", " ", en.strip().strip('"')) == collapsed:
            return zh
    raw, tokens = protect_tokens(text)
    raw = apply_card_names(raw)
    raw = _apply_name_parts(raw)
    raw = apply_phrases(raw, _EFFECT_PHRASES_SORTED)
    raw = apply_words(raw)
    raw = polish_copy(raw)
    return restore_tokens(raw, tokens)


def translate_label(text: str) -> str:
    mapping = [
        ("Ongoing Trophy:", "持续战利品："),
        ("Event Trophy:", "事件战利品："),
        ("MULTI-UNITE:", "多重联合："),
        ("Rally: Enlightened", "集结：圣贤"),
        ("Rally: Lifebound", "集结：命约"),
        ("Rally: Mechana", "集结：机械"),
        ("Rally: Void", "集结：虚空"),
        ("Rally: Monster", "集结：怪物"),
        ("Reward:", "奖励："),
        ("FATE:", "天命："),
        ("Fate:", "天命："),
        ("Trophy:", "战利品："),
        ("Unite:", "联合："),
        ("Energize", "充能"),
        ("ONGOING:", "持续："),
        ("DAY:", "昼："),
        ("NIGHT:", "夜："),
        ("INFEST - ", "感染 - "),
        ("SERENITY:", "宁静："),
        ("ECHO:", "回响："),
        ("Dreambind:", "梦缚："),
    ]
    raw, tokens = protect_tokens(text)
    for en, zh in sorted(mapping, key=lambda x: len(x[0]), reverse=True):
        raw = raw.replace(en, zh)
        raw = raw.replace(en.upper(), zh)
        raw = raw.replace(en.title(), zh)
    return restore_tokens(raw, tokens)
